# SPDX-FileCopyrightText: 2022 Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences
# SPDX-FileCopyrightText: 2022 Matthias Rüster (GFZ) <matthias.ruester@gfz-potsdam.de>
#
# SPDX-License-Identifier: Apache-2.0

FROM node:18.5-buster-slim

WORKDIR /app

VOLUME [ "/app" ]

EXPOSE 3000

CMD [ "sh", "-c", "yarn install ; yarn dev" ]
