// SPDX-FileCopyrightText: 2026 Dusan Mijatovic (Netherlands eScience Center)
// SPDX-FileCopyrightText: 2026 Netherlands eScience Center
//
// SPDX-License-Identifier: Apache-2.0

import {createDebounceValidator} from './debounceFormValidator'

/**
 * Test generated by Google AI Mode based on the function content!
*/

let mockFn: jest.Mock

beforeEach(() => {
  // 1. Tell Jest to control all setTimeout/clearTimeout calls
  jest.useFakeTimers()

  // 2. Create a clean mock function for each test
  mockFn = jest.fn().mockResolvedValue(true)
})

afterEach(() => {
  // 3. Clean up timers and clear global timeout states
  jest.clearAllTimers()
  jest.useRealTimers()
})

it('should resolve with the function result after the default delay (500ms)', async () => {
  const debounceValidator = createDebounceValidator(mockFn, {userId: '123', name:'Test name'})

  // Execute the returned validator function
  const promise = debounceValidator('test-value')

  // Ensure the function hasn't been called immediately
  expect(mockFn).not.toHaveBeenCalled()

  // Fast-forward time past the default 500ms mark
  jest.advanceTimersByTime(500)

  // Wait for the inner mockFn promise to resolve
  const result = await promise

  expect(mockFn).toHaveBeenCalledWith({userId: '123', name:'Test name', value: 'test-value'})
  expect(result).toBe(true)
})

it('should respect a custom delay parameter', async () => {
  const validator = createDebounceValidator(mockFn, {userId: '123'}, 1000)
  const promise = validator('custom-delay')

  // Fast-forward partially; it shouldn't execute yet
  jest.advanceTimersByTime(500)
  expect(mockFn).not.toHaveBeenCalled()

  // Finish the remaining time
  jest.advanceTimersByTime(500)

  await promise
  expect(mockFn).toHaveBeenCalledTimes(1)
})

it('should debounce consecutive calls and only execute the final one', async () => {
  const validator = createDebounceValidator(mockFn, {token: 'abc'}, 300)

  // Trigger three rapid inputs
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const promise1 = validator('d')
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const promise2 = validator('de')
  const promise3 = validator('def')

  // Advance time close to the threshold
  jest.advanceTimersByTime(299)
  expect(mockFn).not.toHaveBeenCalled()

  // Cross the 300ms threshold
  jest.advanceTimersByTime(1)

  // Only the final promise should resolve successfully with the latest value
  await promise3

  expect(mockFn).toHaveBeenCalledTimes(1)
  expect(mockFn).toHaveBeenCalledWith({token: 'abc', value: 'def'})
})

