FROM node:17.3.0-alpine3.14
WORKDIR /usr/app
RUN npm install newman@5.3.0 wait-on@6.0.0
COPY tests/RSD-SaaS-auth.postman_collection.json /usr/app
CMD npx wait-on --timeout 10000 $NEXT_PUBLIC_POSTGREST_URL && npx newman run RSD-SaaS-auth.postman_collection.json --global-var "jwt_secret=$PGRST_JWT_SECRET"
