-- SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
-- SPDX-FileCopyrightText: 2022 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
-- SPDX-FileCopyrightText: 2022 Netherlands eScience Center
-- SPDX-FileCopyrightText: 2022 dv4all
--
-- SPDX-License-Identifier: Apache-2.0

-- RESEARCH DOMAINS

-- create table for RSE research domains
CREATE TABLE research_domain (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	key VARCHAR(50) UNIQUE NOT NULL,
	name VARCHAR(200),
	description VARCHAR(500),
	parent UUID REFERENCES research_domain (id)
);

CREATE FUNCTION check_cycle_research_domain() RETURNS TRIGGER STABLE LANGUAGE plpgsql SECURITY DEFINER AS
$$
DECLARE initial_rd UUID = NEW.id;
DECLARE current_rd UUID = NEW.parent;
BEGIN
	WHILE current_rd IS NOT NULL LOOP
		IF current_rd = initial_rd THEN
			RAISE EXCEPTION USING MESSAGE = 'Cycle detected for research domain with id ' || NEW.id;
		END IF;
		SELECT parent FROM research_domain WHERE id = current_rd INTO current_rd;
	END LOOP;
	RETURN NEW;
END
$$;

-- z_ prefix so that if is executed after the sanitise_update_organisation trigger
CREATE TRIGGER z_check_cycle_research_domain BEFORE UPDATE OF parent ON research_domain FOR EACH ROW EXECUTE PROCEDURE check_cycle_research_domain();


CREATE FUNCTION sanitise_insert_research_domain() RETURNS TRIGGER LANGUAGE plpgsql AS
$$
BEGIN
	NEW.id = gen_random_uuid();
	return NEW;
END
$$;

CREATE TRIGGER sanitise_insert_research_domain BEFORE INSERT ON research_domain FOR EACH ROW EXECUTE PROCEDURE sanitise_insert_research_domain();


CREATE FUNCTION sanitise_update_research_domain() RETURNS TRIGGER LANGUAGE plpgsql AS
$$
BEGIN
	NEW.id = OLD.id;
	return NEW;
END
$$;

CREATE TRIGGER sanitise_update_research_domain BEFORE UPDATE ON research_domain FOR EACH ROW EXECUTE PROCEDURE sanitise_update_research_domain();


-- create reference table for projects
CREATE TABLE research_domain_for_project (
	project UUID REFERENCES project (id),
	research_domain UUID REFERENCES research_domain (id),
	PRIMARY KEY (project, research_domain)
);


-- insert RSE list of research domains

-- level 1
INSERT INTO research_domain (key, name, description, parent) VALUES
	('PE', 'Physical Sciences and Engineering', 'Physical Sciences and Engineering (PE)', null),
	('LS', 'Life Sciences', 'Life Sciences (LS)', null),
	('SH', 'Social Sciences and Humanities', 'Social Sciences and Humanities (SH)', null)
;

-- level 2
INSERT INTO research_domain (key,name,description,parent)
VALUES
	('PE1', 'Mathematics', 'All areas of mathematics, pure and applied, plus mathematical foundations of computer science,mathematical physics and statistics (PE1)', (SELECT id FROM research_domain WHERE key='PE')),
	('PE2', 'Fundamental Constituents of Matter', 'Particle, nuclear, plasma, atomic, molecular, gas, and optical physics (PE2)', (SELECT id FROM research_domain WHERE key='PE')),
	('PE3', 'Condensed Matter Physics', 'Structure, electronic properties, fluids, nanosciences, biological physics (PE3)', (SELECT id FROM research_domain WHERE key='PE')),
	('PE4', 'Physical and Analytical Chemical Sciences', 'Analytical chemistry, chemical theory, physical chemistry/chemical physics (PE4)', (SELECT id FROM research_domain WHERE key='PE')),
	('PE5', 'Synthetic Chemistry and Materials', 'New materials and new synthetic approaches, structure-properties relations, solid state chemistry, molecular architecture, organic chemistry (PE5)', (SELECT id FROM research_domain WHERE key='PE')),
	('PE6', 'Computer Science and Informatics', 'Informatics and information systems, computer science, scientific computing, intelligent systems (PE6)', (SELECT id FROM research_domain WHERE key='PE')),
	('PE7', 'Systems and Communication Engineering', 'Electrical, electronic, communication, optical and systems engineering (PE7)', (SELECT id FROM research_domain WHERE key='PE')),
	('PE8', 'Products and Processes Engineering', 'Product and process design, chemical, civil, environmental, mechanical, vehicle engineering, energy processes and relevant computational methods (PE8)', (SELECT id FROM research_domain WHERE key='PE')),
	('PE9', 'Universe Sciences', 'Astro-physics/-chemistry/-biology; solar system; planetary systems; stellar, galactic and extragalactic astronomy; cosmology; space sciences; astronomical instrumentation and data (PE9)', (SELECT id FROM research_domain WHERE key='PE')),
	('PE10', 'Earth System Science', 'Physical geography, geology, geophysics, atmospheric sciences, oceanography, climatology, cryology, ecology, global environmental change, biogeochemical cycles, natural resources management (PE10)', (SELECT id FROM research_domain WHERE key='PE')),
	('PE11', 'Materials Engineering', 'Advanced materials development: performance enhancement, modelling, large-scale preparation,modification, tailoring, optimisation, novel and combined use of materials, etc. (PE11)', (SELECT id FROM research_domain WHERE key='PE')),
	('LS1', 'Molecules of Life: Biological Mechanisms, Structures and Functions', 'For all organisms: Molecular biology, biochemistry, structural biology, molecular biophysics, synthetic and chemical biology, drug design, innovative methods and modelling (LS1)', (SELECT id FROM research_domain WHERE key='LS')),
	('LS2', 'Integrative Biology: from Genes and Genomes to Systems', 'For all organisms: Genetics, epigenetics, genomics and other ‘omics studies, bioinformatics, systems biology, genetic diseases, gene editing, innovative methods and modelling, ‘omics for personalised medicine (LS2)', (SELECT id FROM research_domain WHERE key='LS')),
	('LS3', 'Cellular, Developmental and Regenerative Biology', 'For all organisms: Structure and function of the cell, cell-cell communication, embryogenesis, tissue differentiation, organogenesis, growth, development, evolution of development, organoids, stem cells, regeneration, therapeutic approaches (LS3)', (SELECT id FROM research_domain WHERE key='LS')),
	('LS4', 'Physiology in Health, Disease and Ageing', 'Organ and tissue physiology, comparative physiology, physiology of ageing, pathophysiology, inter-organ and tissue communication, endocrinology, nutrition, metabolism, interaction with the microbiome, non-communicable diseases including cancer (and except disorders of the nervous system and immunity-related diseases) (LS4)', (SELECT id FROM research_domain WHERE key='LS')),
	('LS5', 'Neuroscience and Disorders of the Nervous System', 'Nervous system development, homeostasis and ageing, nervous system function and dysfunction, systems neuroscience and modelling, biological basis of cognitive processes and of behaviour, neurological and mental disorders (LS5)', (SELECT id FROM research_domain WHERE key='LS')),
	('LS6', 'Immunity, Infection and Immunotherapy', 'The immune system, related disorders and their mechanisms, biology of infectious agents and infection, biological basis of prevention and treatment of infectious diseases, innovative immunological tools and approaches, including therapies (LS6)', (SELECT id FROM research_domain WHERE key='LS')),
	('LS7', 'Prevention, Diagnosis and Treatment of Human Diseases', 'Medical technologies and tools for prevention, diagnosis and treatment of human diseases, therapeutic approaches and interventions, pharmacology, preventative medicine, epidemiology and public health, digital medicine (LS7)', (SELECT id FROM research_domain WHERE key='LS')),
	('LS8', 'Environmental Biology, Ecology and Evolution', 'For all organisms: Ecology, biodiversity, environmental change, evolutionary biology, behavioural ecology, microbial ecology, marine biology, ecophysiology, theoretical developments and modelling (LS8)', (SELECT id FROM research_domain WHERE key='LS')),
	('LS9', 'Biotechnology and Biosystems Engineering', 'Biotechnology using all organisms, biotechnology for environment and food applications, applied plant and animal sciences, bioengineering and synthetic biology, biomass and biofuels, biohazards (LS9)', (SELECT id FROM research_domain WHERE key='LS')),
	('SH1', 'Individuals, Markets and Organisations', 'Economics, finance, management (SH1)', (SELECT id FROM research_domain WHERE key='SH')),
	('SH2', 'Institutions, Governance and Legal Systems', 'Political science, international relations, law (SH2)', (SELECT id FROM research_domain WHERE key='SH')),
	('SH3', 'The Social World and Its Diversity', 'Sociology, social psychology, social anthropology, education sciences, communication studies (SH3)', (SELECT id FROM research_domain WHERE key='SH')),
	('SH4', 'The Human Mind and Its Complexity', 'Cognitive science, psychology, linguistics, theoretical philosophy (SH4)', (SELECT id FROM research_domain WHERE key='SH')),
	('SH5', 'Cultures and Cultural Production', 'Literary studies, cultural studies, study of the arts, philosophy (SH5)', (SELECT id FROM research_domain WHERE key='SH')),
	('SH6', 'The Study of the Human Past', 'Archaeology and history (SH6)', (SELECT id FROM research_domain WHERE key='SH')),
	('SH7', 'Human Mobility, Environment, and Space', 'Human geography, demography, health, sustainability science, territorial planning, spatial analysis (SH7)', (SELECT id FROM research_domain WHERE key='SH'))
;


-- level 3

INSERT INTO research_domain (key,name,description,parent)
VALUES
	('PE1_1', 'Logic and foundations', 'Logic and foundations (PE1_1)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_2', 'Algebra', 'Algebra (PE1_2)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_3', 'Number theory', 'Number theory (PE1_3)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_4', 'Algebraic and complex geometry', 'Algebraic and complex geometry (PE1_4)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_5', 'Lie groups, Lie algebras', 'Lie groups, Lie algebras (PE1_5)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_6', 'Geometry and global analysis', 'Geometry and global analysis (PE1_6)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_7', 'Topology', 'Topology (PE1_7)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_8', 'Analysis', 'Analysis (PE1_8)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_9', 'Operator algebras and functional analysis', 'Operator algebras and functional analysis (PE1_9)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_10', 'ODE and dynamical systems', 'ODE and dynamical systems (PE1_10)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_11', 'Theoretical aspects of partial differential equations', 'Theoretical aspects of partial differential equations (PE1_11)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_12', 'Mathematical physics', 'Mathematical physics (PE1_12)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_13', 'Probability', 'Probability (PE1_13)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_14', 'Mathematical statistics', 'Mathematical statistics (PE1_14)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_15', 'Generic statistical methodology and modelling', 'Generic statistical methodology and modelling (PE1_15)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_16', 'Discrete mathematics and combinatorics', 'Discrete mathematics and combinatorics (PE1_16)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_17', 'Mathematical aspects of computer science', 'Mathematical aspects of computer science (PE1_17)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_18', 'Numerical analysis', 'Numerical analysis (PE1_18)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_19', 'Scientific computing and data processing', 'Scientific computing and data processing (PE1_19)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_20', 'Control theory, optimisation and operational research', 'Control theory, optimisation and operational research (PE1_20)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_21', 'Application of mathematics in sciences', 'Application of mathematics in sciences (PE1_21)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE1_22', 'Application of mathematics in industry and society', 'Application of mathematics in industry and society (PE1_22)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE2_1', 'Theory of fundamental interactions', 'Theory of fundamental interactions (PE2_1)', (SELECT id FROM research_domain WHERE key='PE1')),
	('PE2_2', 'Phenomenology of fundamental interactions', 'Phenomenology of fundamental interactions (PE2_2)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_3', 'Experimental particle physics with accelerators', 'Experimental particle physics with accelerators (PE2_3)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_4', 'Experimental particle physics without accelerators', 'Experimental particle physics without accelerators (PE2_4)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_5', 'Classical and quantum physics of gravitational interactions', 'Classical and quantum physics of gravitational interactions (PE2_5)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_6', 'Nuclear, hadron and heavy ion physics', 'Nuclear, hadron and heavy ion physics (PE2_6)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_7', 'Nuclear and particle astrophysics', 'Nuclear and particle astrophysics (PE2_7)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_8', 'Gas and plasma physics', 'Gas and plasma physics (PE2_8)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_9', 'Electromagnetism', 'Electromagnetism (PE2_9)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_10', 'Atomic, molecular physics', 'Atomic, molecular physics (PE2_10)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_11', 'Ultra-cold atoms and molecules', 'Ultra-cold atoms and molecules (PE2_11)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_12', 'Optics, non-linear optics and nano-optics', 'Optics, non-linear optics and nano-optics (PE2_12)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_13', 'Quantum optics and quantum information', 'Quantum optics and quantum information (PE2_13)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_14', 'Lasers, ultra-short lasers and laser physics', 'Lasers, ultra-short lasers and laser physics (PE2_14)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_15', 'Thermodynamics', 'Thermodynamics (PE2_15)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_16', 'Non-linear physics', 'Non-linear physics (PE2_16)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_17', 'Metrology and measurement', 'Metrology and measurement (PE2_17)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE2_18', 'Equilibrium and non-equilibrium statistical mechanics: steady states and dynamics', 'Equilibrium and non-equilibrium statistical mechanics: steady states and dynamics (PE2_18)', (SELECT id FROM research_domain WHERE key='PE2')),
	('PE3_1', 'Structure of solids, material growth and characterisation', 'Structure of solids, material growth and characterisation (PE3_1)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_2', 'Mechanical and acoustical properties of condensed matter, lattice dynamics', 'Mechanical and acoustical properties of condensed matter, lattice dynamics (PE3_2)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_3', 'Transport properties of condensed matter', 'Transport properties of condensed matter (PE3_3)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_4', 'Electronic properties of materials, surfaces, interfaces, nanostructures', 'Electronic properties of materials, surfaces, interfaces, nanostructures (PE3_4)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_5', 'Physical properties of semiconductors and insulators', 'Physical properties of semiconductors and insulators (PE3_5)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_6', 'Macroscopic quantum phenomena, e.g. superconductivity, superfluidity, quantum Hall effect', 'Macroscopic quantum phenomena, e.g. superconductivity, superfluidity, quantum Hall effect (PE3_6)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_7', 'Spintronics', 'Spintronics (PE3_7)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_8', 'Magnetism and strongly correlated systems', 'Magnetism and strongly correlated systems (PE3_8)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_9', 'Condensed matter – beam interactions (photons, electrons, etc.)', 'Condensed matter – beam interactions (photons, electrons, etc.) (PE3_9)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_10', 'Nanophysics, e.g. nanoelectronics, nanophotonics, nanomagnetism, nanoelectromechanics', 'Nanophysics, e.g. nanoelectronics, nanophotonics, nanomagnetism, nanoelectromechanics (PE3_10)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_11', 'Mesoscopic quantum physics and solid-state quantum technologies', 'Mesoscopic quantum physics and solid-state quantum technologies (PE3_11)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_12', 'Molecular electronics', 'Molecular electronics (PE3_12)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_13', 'Structure and dynamics of disordered systems, e.g. soft matter (gels, colloids, liquid crystals), granular matter, liquids, glasses, defects', 'Structure and dynamics of disordered systems, e.g. soft matter (gels, colloids, liquid crystals), granular matter, liquids, glasses, defects (PE3_13)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_14', 'Fluid dynamics (physics)', 'Fluid dynamics (physics) (PE3_14)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_15', 'Statistical physics: phase transitions, condensed matter systems, models of complex systems, interdisciplinary applications', 'Statistical physics: phase transitions, condensed matter systems, models of complex systems, interdisciplinary applications (PE3_15)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE3_16', 'Physics of biological systems', 'Physics of biological systems (PE3_16)', (SELECT id FROM research_domain WHERE key='PE3')),
	('PE4_1', 'Physical chemistry', 'Physical chemistry (PE4_1)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_2', 'Spectroscopic and spectrometric techniques', 'Spectroscopic and spectrometric techniques (PE4_2)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_3', 'Molecular architecture and Structure', 'Molecular architecture and Structure (PE4_3)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_4', 'Surface science and nanostructures', 'Surface science and nanostructures (PE4_4)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_5', 'Analytical chemistry', 'Analytical chemistry (PE4_5)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_6', 'Chemical physics', 'Chemical physics (PE4_6)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_7', 'Chemical instrumentation', 'Chemical instrumentation (PE4_7)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_8', 'Electrochemistry, electrodialysis, microfluidics, sensors', 'Electrochemistry, electrodialysis, microfluidics, sensors (PE4_8)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_9', 'Method development in chemistry', 'Method development in chemistry (PE4_9)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_10', 'Heterogeneous catalysis', 'Heterogeneous catalysis (PE4_10)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_11', 'Physical chemistry of biological systems', 'Physical chemistry of biological systems (PE4_11)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_12', 'Chemical reactions: mechanisms, dynamics, kinetics and catalytic reactions', 'Chemical reactions: mechanisms, dynamics, kinetics and catalytic reactions (PE4_12)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_13', 'Theoretical and computational chemistry', 'Theoretical and computational chemistry (PE4_13)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_14', 'Radiation and Nuclear chemistry', 'Radiation and Nuclear chemistry (PE4_14)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_15', 'Photochemistry', 'Photochemistry (PE4_15)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_16', 'Corrosion', 'Corrosion (PE4_16)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_17', 'Characterisation methods of materials', 'Characterisation methods of materials (PE4_17)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE4_18', 'Environment chemistry', 'Environment chemistry (PE4_18)', (SELECT id FROM research_domain WHERE key='PE4')),
	('PE5_1', 'Structural properties of materials', 'Structural properties of materials (PE5_1)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_2', 'Solid state materials chemistry', 'Solid state materials chemistry (PE5_2)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_3', 'Surface modification', 'Surface modification (PE5_3)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_4', 'Thin films', 'Thin films (PE5_4)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_5', 'Ionic liquids', 'Ionic liquids (PE5_5)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_6', 'New materials: oxides, alloys, composite, organic-inorganic hybrid, nanoparticles', 'New materials: oxides, alloys, composite, organic-inorganic hybrid, nanoparticles (PE5_6)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_7', 'Biomaterials synthesis', 'Biomaterials synthesis (PE5_7)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_8', 'Intelligent materials synthesis – self assembled materials', 'Intelligent materials synthesis – self assembled materials (PE5_8)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_9', 'Coordination chemistry', 'Coordination chemistry (PE5_9)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_10', 'Colloid chemistry', 'Colloid chemistry (PE5_10)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_11', 'Biological chemistry and chemical biology', 'Biological chemistry and chemical biology (PE5_11)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_12', 'Chemistry of condensed matter', 'Chemistry of condensed matter (PE5_12)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_13', 'Homogeneous catalysis', 'Homogeneous catalysis (PE5_13)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_14', 'Macromolecular chemistry', 'Macromolecular chemistry (PE5_14)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_15', 'Polymer chemistry', 'Polymer chemistry (PE5_15)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_16', 'Supramolecular chemistry', 'Supramolecular chemistry (PE5_16)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_17', 'Organic chemistry', 'Organic chemistry (PE5_17)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE5_18', 'Medicinal chemistry', 'Medicinal chemistry (PE5_18)', (SELECT id FROM research_domain WHERE key='PE5')),
	('PE6_1', 'Computer architecture, embedded systems, operating systems', 'Computer architecture, embedded systems, operating systems (PE6_1)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_2', 'Distributed systems, parallel computing, sensor networks, cyber-physical systems', 'Distributed systems, parallel computing, sensor networks, cyber-physical systems (PE6_2)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_3', 'Software engineering, programming languages and systems', 'Software engineering, programming languages and systems (PE6_3)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_4', 'Theoretical computer science, formal methods, automata', 'Theoretical computer science, formal methods, automata (PE6_4)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_5', 'Security, privacy, cryptology, quantum cryptography', 'Security, privacy, cryptology, quantum cryptography (PE6_5)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_6', 'Algorithms and complexity, distributed, parallel and network algorithms, algorithmic game theory', 'Algorithms and complexity, distributed, parallel and network algorithms, algorithmic game theory (PE6_6)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_7', 'Artificial intelligence, intelligent systems, natural language processing', 'Artificial intelligence, intelligent systems, natural language processing (PE6_7)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_8', 'Computer graphics, computer vision, multimedia, computer games', 'Computer graphics, computer vision, multimedia, computer games (PE6_8)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_9', 'Human computer interaction and interface, visualisation', 'Human computer interaction and interface, visualisation (PE6_9)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_10', 'Web and information systems, data management systems, information retrieval and digital libraries, data fusion', 'Web and information systems, data management systems, information retrieval and digital libraries, data fusion (PE6_10)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_11', 'Machine learning, statistical data processing and applications using signal processing ( e.g. speech,image,video)', 'Machine learning, statistical data processing and applications using signal processing ( e.g. speech,image,video) (PE6_11)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_12', 'Scientific computing, simulation and modelling tools', 'Scientific computing, simulation and modelling tools (PE6_12)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_13', 'Bioinformatics, bio-inspired computing, and natural computing', 'Bioinformatics, bio-inspired computing, and natural computing (PE6_13)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE6_14', 'Quantum computing (formal methods, algorithms and other computer science aspects)', 'Quantum computing (formal methods, algorithms and other computer science aspects) (PE6_14)', (SELECT id FROM research_domain WHERE key='PE6')),
	('PE7_1', 'Control engineering', 'Control engineering (PE7_1)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_2', 'Electrical engineering: power components and/or systems', 'Electrical engineering: power components and/or systems (PE7_2)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_3', 'Simulation engineering and modelling', 'Simulation engineering and modelling (PE7_3)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_4', '(Micro- and nano-) systems engineering', '(Micro- and nano-) systems engineering (PE7_4)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_5', '(Micro- and nano-) electronic, optoelectronic and photonic components', '(Micro- and nano-) electronic, optoelectronic and photonic components (PE7_5)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_6', 'Communication systems, wireless technology, high-frequency technology', 'Communication systems, wireless technology, high-frequency technology (PE7_6)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_7', 'Signal processing', 'Signal processing (PE7_7)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_8', 'Networks, e.g. communication networks and nodes, Internet of Things, sensor networks, networks of robots', 'Networks, e.g. communication networks and nodes, Internet of Things, sensor networks, networks of robots (PE7_8)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_9', 'Man-machine interfaces', 'Man-machine interfaces (PE7_9)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_10', 'Robotics', 'Robotics (PE7_10)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_11', 'Components and systems for applications (in e.g. medicine, biology, environment)', 'Components and systems for applications (in e.g. medicine, biology, environment) (PE7_11)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE7_12', 'Electrical energy production, distribution, applications', 'Electrical energy production, distribution, applications (PE7_12)', (SELECT id FROM research_domain WHERE key='PE7')),
	('PE8_1', 'Aerospace engineering', 'Aerospace engineering (PE8_1)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_2', 'Chemical engineering, technical chemistry', 'Chemical engineering, technical chemistry (PE8_2)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_3', 'Civil engineering, architecture, offshore construction, lightweight construction, geotechnics', 'Civil engineering, architecture, offshore construction, lightweight construction, geotechnics (PE8_3)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_4', 'Computational engineering', 'Computational engineering (PE8_4)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_5', 'Fluid mechanics', 'Fluid mechanics (PE8_5)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_6', 'Energy processes engineering', 'Energy processes engineering (PE8_6)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_7', 'Mechanical engineering', 'Mechanical engineering (PE8_7)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_8', 'Propulsion engineering, e.g. hydraulic, turbo, piston, hybrid engines', 'Propulsion engineering, e.g. hydraulic, turbo, piston, hybrid engines (PE8_8)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_9', 'Production technology, process engineering', 'Production technology, process engineering (PE8_9)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_10', 'Manufacturing engineering and industrial design', 'Manufacturing engineering and industrial design (PE8_10)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_11', 'Environmental engineering, e.g. sustainable design, waste and water treatment, recycling, regeneration or recovery of compounds, carbon capture & storage', 'Environmental engineering, e.g. sustainable design, waste and water treatment, recycling, regeneration or recovery of compounds, carbon capture & storage (PE8_11)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_12', 'Naval/marine engineering', 'Naval/marine engineering (PE8_12)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_13', 'Industrial bioengineering', 'Industrial bioengineering (PE8_13)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE8_14', 'Automotive and rail engineering; multi-/inter-modal transport engineering', 'Automotive and rail engineering; multi-/inter-modal transport engineering (PE8_14)', (SELECT id FROM research_domain WHERE key='PE8')),
	('PE9_1', 'Solar physics – the Sun and the heliosphere', 'Solar physics – the Sun and the heliosphere (PE9_1)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_2', 'Solar system science', 'Solar system science (PE9_2)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_3', 'Exoplanetary science, formation and characterization of extrasolar planets', 'Exoplanetary science, formation and characterization of extrasolar planets (PE9_3)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_4', 'Astrobiology', 'Astrobiology (PE9_4)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_5', 'Interstellar medium and star formation', 'Interstellar medium and star formation (PE9_5)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_6', 'Stars – stellar physics, stellar systems', 'Stars – stellar physics, stellar systems (PE9_6)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_7', 'The Milky Way', 'The Milky Way (PE9_7)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_8', 'Galaxies – formation, evolution, clusters', 'Galaxies – formation, evolution, clusters (PE9_8)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_9', 'Cosmology and large-scale structure, dark matter, dark energy', 'Cosmology and large-scale structure, dark matter, dark energy (PE9_9)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_10', 'Relativistic astrophysics and compact objects', 'Relativistic astrophysics and compact objects (PE9_10)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_11', 'Gravitational wave astronomy', 'Gravitational wave astronomy (PE9_11)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_12', 'High-energy and particle astronomy', 'High-energy and particle astronomy (PE9_12)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE9_13', 'Astronomical instrumentation and data, e.g. telescopes, detectors, techniques, archives, analyses', 'Astronomical instrumentation and data, e.g. telescopes, detectors, techniques, archives, analyses (PE9_13)', (SELECT id FROM research_domain WHERE key='PE9')),
	('PE10_1', 'Atmospheric chemistry, atmospheric composition, air pollution', 'Atmospheric chemistry, atmospheric composition, air pollution (PE10_1)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_2', 'Meteorology, atmospheric physics and dynamics', 'Meteorology, atmospheric physics and dynamics (PE10_2)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_3', 'Climatology and climate change', 'Climatology and climate change (PE10_3)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_4', 'Terrestrial ecology, land cover change', 'Terrestrial ecology, land cover change (PE10_4)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_5', 'Geology, tectonics, volcanology', 'Geology, tectonics, volcanology (PE10_5)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_6', 'Palaeoclimatology, palaeoecology', 'Palaeoclimatology, palaeoecology (PE10_6)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_7', 'Physics of earth’s interior, seismology, geodynamics', 'Physics of earth’s interior, seismology, geodynamics (PE10_7)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_8', 'Oceanography (physical, chemical, biological, geological)', 'Oceanography (physical, chemical, biological, geological) (PE10_8)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_9', 'Biogeochemistry, biogeochemical cycles, environmental chemistry', 'Biogeochemistry, biogeochemical cycles, environmental chemistry (PE10_9)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_10', 'Mineralogy, petrology, igneous petrology, metamorphic petrology', 'Mineralogy, petrology, igneous petrology, metamorphic petrology (PE10_10)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_11', 'Geochemistry, cosmochemistry, crystal chemistry, isotope geochemistry, thermodynamics', 'Geochemistry, cosmochemistry, crystal chemistry, isotope geochemistry, thermodynamics (PE10_11)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_12', 'Sedimentology, soil science, palaeontology, earth evolution', 'Sedimentology, soil science, palaeontology, earth evolution (PE10_12)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_13', 'Physical geography, geomorphology', 'Physical geography, geomorphology (PE10_13)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_14', 'Earth observations from space/remote sensing', 'Earth observations from space/remote sensing (PE10_14)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_15', 'Geomagnetism, palaeomagnetism', 'Geomagnetism, palaeomagnetism (PE10_15)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_16', 'Ozone, upper atmosphere, ionosphere', 'Ozone, upper atmosphere, ionosphere (PE10_16)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_17', 'Hydrology, hydrogeology, engineering and environmental geology, water and soil pollution', 'Hydrology, hydrogeology, engineering and environmental geology, water and soil pollution (PE10_17)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_18', 'Cryosphere, dynamics of snow and ice cover, sea ice, permafrosts and ice sheets', 'Cryosphere, dynamics of snow and ice cover, sea ice, permafrosts and ice sheets (PE10_18)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_19', 'Planetary geology and geophysics', 'Planetary geology and geophysics (PE10_19)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_20', 'Geohazards', 'Geohazards (PE10_20)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE10_21', 'Earth system modelling and interactions', 'Earth system modelling and interactions (PE10_21)', (SELECT id FROM research_domain WHERE key='PE10')),
	('PE11_1', 'Engineering of biomaterials, biomimetic, bioinspired and bio-enabled materials', 'Engineering of biomaterials, biomimetic, bioinspired and bio-enabled materials (PE11_1)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_2', 'Engineering of metals and alloys', 'Engineering of metals and alloys (PE11_2)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_3', 'Engineering of ceramics and glasses', 'Engineering of ceramics and glasses (PE11_3)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_4', 'Engineering of polymers and plastics', 'Engineering of polymers and plastics (PE11_4)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_5', 'Engineering of composites and hybrid materials', 'Engineering of composites and hybrid materials (PE11_5)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_6', 'Engineering of carbon materials', 'Engineering of carbon materials (PE11_6)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_7', 'Engineering of metal oxides', 'Engineering of metal oxides (PE11_7)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_8', 'Engineering of alternative established or emergent materials', 'Engineering of alternative established or emergent materials (PE11_8)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_9', 'Nanomaterials engineering, e.g. nanoparticles, nanoporous materials, 1D & 2D nanomaterials', 'Nanomaterials engineering, e.g. nanoparticles, nanoporous materials, 1D & 2D nanomaterials (PE11_9)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_10', 'Soft materials engineering, e.g. gels, foams, colloids', 'Soft materials engineering, e.g. gels, foams, colloids (PE11_10)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_11', 'Porous materials engineering, e.g. covalent-organic, metal-organic, porous aromatic frameworks', 'Porous materials engineering, e.g. covalent-organic, metal-organic, porous aromatic frameworks (PE11_11)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_12', 'Semi-conducting and magnetic materials engineering', 'Semi-conducting and magnetic materials engineering (PE11_12)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_13', 'Metamaterials engineering', 'Metamaterials engineering (PE11_13)', (SELECT id FROM research_domain WHERE key='PE11')),
	('PE11_14', 'Computational methods for materials engineering', 'Computational methods for materials engineering (PE11_14)', (SELECT id FROM research_domain WHERE key='PE11')),
	('LS1_1', 'Macromolecular complexes including interactions involving nucleic acids, proteins, lipids and carbohydrates', 'Macromolecular complexes including interactions involving nucleic acids, proteins, lipids and carbohydrates (LS1_1)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_2', 'Biochemistry', 'Biochemistry (LS1_2)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_3', 'DNA and RNA biology', 'DNA and RNA biology (LS1_3)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_4', 'Protein biology', 'Protein biology (LS1_4)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_5', 'Lipid biology', 'Lipid biology (LS1_5)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_6', 'Glycobiology', 'Glycobiology (LS1_6)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_7', 'Molecular biophysics, biomechanics, bioenergetics', 'Molecular biophysics, biomechanics, bioenergetics (LS1_7)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_8', 'Structural biology', 'Structural biology (LS1_8)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_9', 'Molecular mechanisms of signalling processes', 'Molecular mechanisms of signalling processes (LS1_9)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_10', 'Synthetic biology', 'Synthetic biology (LS1_10)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_11', 'Chemical biology', 'Chemical biology (LS1_11)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_12', 'Protein design', 'Protein design (LS1_12)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_13', 'Early translational research and drug design', 'Early translational research and drug design (LS1_13)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS1_14', 'Innovative methods and modelling in molecular, structural and synthetic biology', 'Innovative methods and modelling in molecular, structural and synthetic biology (LS1_14)', (SELECT id FROM research_domain WHERE key='LS1')),
	('LS2_1', 'Genetics', 'Genetics (LS2_1)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_2', 'Gene editing', 'Gene editing (LS2_2)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_3', 'Epigenetics', 'Epigenetics (LS2_3)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_4', 'Gene regulation', 'Gene regulation (LS2_4)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_5', 'Genomics', 'Genomics (LS2_5)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_6', 'Metagenomics', 'Metagenomics (LS2_6)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_7', 'Transcriptomics', 'Transcriptomics (LS2_7)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_8', 'Proteomics', 'Proteomics (LS2_8)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_9', 'Metabolomics', 'Metabolomics (LS2_9)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_10', 'Glycomics/Lipidomics', 'Glycomics/Lipidomics (LS2_10)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_11', 'Bioinformatics and computational biology', 'Bioinformatics and computational biology (LS2_11)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_12', 'Biostatistics', 'Biostatistics (LS2_12)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_13', 'Systems biology', 'Systems biology (LS2_13)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_14', 'Genetic diseases', 'Genetic diseases (LS2_14)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_15', 'Integrative biology for personalised medicine', 'Integrative biology for personalised medicine (LS2_15)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS2_16', 'Innovative methods and modelling in integrative biology', 'Innovative methods and modelling in integrative biology (LS2_16)', (SELECT id FROM research_domain WHERE key='LS2')),
	('LS3_1', 'Cell cycle, cell division and growth', 'Cell cycle, cell division and growth (LS3_1)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_2', 'Cell senescence, cell death, autophagy, cell ageing', 'Cell senescence, cell death, autophagy, cell ageing (LS3_2)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_3', 'Cell behaviour, including control of cell shape, cell migration', 'Cell behaviour, including control of cell shape, cell migration (LS3_3)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_4', 'Cell junctions, cell adhesion, the extracellular matrix, cell communication', 'Cell junctions, cell adhesion, the extracellular matrix, cell communication (LS3_4)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_5', 'Cell signalling and signal transduction, exosome biology', 'Cell signalling and signal transduction, exosome biology (LS3_5)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_6', 'Organelle biology and trafficking', 'Organelle biology and trafficking (LS3_6)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_7', 'Mechanobiology of cells, tissues and organs', 'Mechanobiology of cells, tissues and organs (LS3_7)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_8', 'Embryogenesis, pattern formation, morphogenesis', 'Embryogenesis, pattern formation, morphogenesis (LS3_8)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_9', 'Cell differentiation, formation of tissues and organs', 'Cell differentiation, formation of tissues and organs (LS3_9)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_10', 'Developmental genetics', 'Developmental genetics (LS3_10)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_11', 'Evolution of developmental strategies', 'Evolution of developmental strategies (LS3_11)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_12', 'Organoids', 'Organoids (LS3_12)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_13', 'Stem cells', 'Stem cells (LS3_13)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_14', 'Regeneration', 'Regeneration (LS3_14)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_15', 'Development of cell-based therapeutic approaches for tissue regeneration', 'Development of cell-based therapeutic approaches for tissue regeneration (LS3_15)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_16', 'Functional imaging of cells and tissues', 'Functional imaging of cells and tissues (LS3_16)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS3_17', 'Theoretical modelling in cellular, developmental and regenerative biology', 'Theoretical modelling in cellular, developmental and regenerative biology (LS3_17)', (SELECT id FROM research_domain WHERE key='LS3')),
	('LS4_1', 'Organ and tissue physiology and pathophysiology', 'Organ and tissue physiology and pathophysiology (LS4_1)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_2', 'Comparative physiology', 'Comparative physiology (LS4_2)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_3', 'Physiology of ageing', 'Physiology of ageing (LS4_3)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_4', 'Endocrinology', 'Endocrinology (LS4_4)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_5', 'Non-hormonal mechanisms of inter-organ and tissue communication', 'Non-hormonal mechanisms of inter-organ and tissue communication (LS4_5)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_6', 'Microbiome and host physiology', 'Microbiome and host physiology (LS4_6)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_7', 'Nutrition and exercise physiology', 'Nutrition and exercise physiology (LS4_7)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_8', 'Impact of stress (including environmental stress) on physiology', 'Impact of stress (including environmental stress) on physiology (LS4_8)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_9', 'Metabolism and metabolic disorders, including diabetes and obesity', 'Metabolism and metabolic disorders, including diabetes and obesity (LS4_9)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_10', 'The cardiovascular system and cardiovascular diseases', 'The cardiovascular system and cardiovascular diseases (LS4_10)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_11', 'Haematopoiesis and blood diseases', 'Haematopoiesis and blood diseases (LS4_11)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_12', 'Cancer', 'Cancer (LS4_12)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS4_13', 'Other non-communicable diseases (except disorders of the nervous system and immunity-related diseases)', 'Other non-communicable diseases (except disorders of the nervous system and immunity-related diseases) (LS4_13)', (SELECT id FROM research_domain WHERE key='LS4')),
	('LS5_1', 'Neuronal cells', 'Neuronal cells (LS5_1)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_2', 'Glial cells and neuronal-glial communication', 'Glial cells and neuronal-glial communication (LS5_2)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_3', 'Neural development and related disorders', 'Neural development and related disorders (LS5_3)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_4', 'Neural stem cells', 'Neural stem cells (LS5_4)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_5', 'Neural networks and plasticity', 'Neural networks and plasticity (LS5_5)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_6', 'Neurovascular biology and blood-brain barrier', 'Neurovascular biology and blood-brain barrier (LS5_6)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_7', 'Sensory systems, sensation and perception, including pain', 'Sensory systems, sensation and perception, including pain (LS5_7)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_8', 'Neural basis of behaviour', 'Neural basis of behaviour (LS5_8)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_9', 'Neural basis of cognition', 'Neural basis of cognition (LS5_9)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_10', 'Ageing of the nervous system', 'Ageing of the nervous system (LS5_10)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_11', 'Neurological and neurodegenerative disorders', 'Neurological and neurodegenerative disorders (LS5_11)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_12', 'Mental disorders', 'Mental disorders (LS5_12)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_13', 'Nervous system injuries and trauma, stroke', 'Nervous system injuries and trauma, stroke (LS5_13)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_14', 'Repair and regeneration of the nervous system', 'Repair and regeneration of the nervous system (LS5_14)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_15', 'Neuroimmunology, neuroinflammation', 'Neuroimmunology, neuroinflammation (LS5_15)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_16', 'Systems and computational neuroscience', 'Systems and computational neuroscience (LS5_16)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_17', 'Imaging in neuroscience', 'Imaging in neuroscience (LS5_17)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS5_18', 'Innovative methods and tools for neuroscience', 'Innovative methods and tools for neuroscience (LS5_18)', (SELECT id FROM research_domain WHERE key='LS5')),
	('LS6_1', 'Innate immunity', 'Innate immunity (LS6_1)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS6_2', 'Adaptive immunity', 'Adaptive immunity (LS6_2)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS6_3', 'Regulation of the immune response', 'Regulation of the immune response (LS6_3)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS6_4', 'Immune-related diseases', 'Immune-related diseases (LS6_4)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS6_5', 'Biology of pathogens (e.g. bacteria, viruses, parasites, fungi)', 'Biology of pathogens (e.g. bacteria, viruses, parasites, fungi) (LS6_5)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS6_6', 'Infectious diseases', 'Infectious diseases (LS6_6)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS6_7', 'Mechanisms of infection', 'Mechanisms of infection (LS6_7)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS6_8', 'Biological basis of prevention and treatment of infection', 'Biological basis of prevention and treatment of infection (LS6_8)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS6_9', 'Antimicrobials, antimicrobial resistance', 'Antimicrobials, antimicrobial resistance (LS6_9)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS6_10', 'Vaccine development', 'Vaccine development (LS6_10)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS6_11', 'Innovative immunological tools and approaches, including therapies', 'Innovative immunological tools and approaches, including therapies (LS6_11)', (SELECT id FROM research_domain WHERE key='LS6')),
	('LS7_1', 'Medical imaging for prevention, diagnosis and monitoring of diseases', 'Medical imaging for prevention, diagnosis and monitoring of diseases (LS7_1)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_2', 'Medical technologies and tools (including genetic tools and biomarkers) for prevention, diagnosis, monitoring and treatment of diseases', 'Medical technologies and tools (including genetic tools and biomarkers) for prevention, diagnosis, monitoring and treatment of diseases (LS7_2)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_3', 'Nanomedicine', 'Nanomedicine (LS7_3)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_4', 'Regenerative medicine', 'Regenerative medicine (LS7_4)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_5', 'Applied gene, cell and immune therapies', 'Applied gene, cell and immune therapies (LS7_5)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_6', 'Other medical therapeutic interventions, including transplantation', 'Other medical therapeutic interventions, including transplantation (LS7_6)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_7', 'Pharmacology and toxicology', 'Pharmacology and toxicology (LS7_7)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_8', 'Effectiveness of interventions, including resistance to therapies', 'Effectiveness of interventions, including resistance to therapies (LS7_8)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_9', 'Public health and epidemiology', 'Public health and epidemiology (LS7_9)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_10', 'Preventative and prognostic medicine', 'Preventative and prognostic medicine (LS7_10)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_11', 'Environmental health, occupational medicine', 'Environmental health, occupational medicine (LS7_11)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_12', 'Health care, including care for the ageing population', 'Health care, including care for the ageing population (LS7_12)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_13', 'Palliative medicine', 'Palliative medicine (LS7_13)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_14', 'Digital medicine, e-medicine, medical applications of artificial intelligence', 'Digital medicine, e-medicine, medical applications of artificial intelligence (LS7_14)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS7_15', 'Medical ethics', 'Medical ethics (LS7_15)', (SELECT id FROM research_domain WHERE key='LS7')),
	('LS8_1', 'Ecosystem and community ecology, macroecology', 'Ecosystem and community ecology, macroecology (LS8_1)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_2', 'Biodiversity', 'Biodiversity (LS8_2)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_3', 'Conservation biology', 'Conservation biology (LS8_3)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_4', 'Population biology, population dynamics, population genetics', 'Population biology, population dynamics, population genetics (LS8_4)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_5', 'Biological aspects of environmental change, including climate change', 'Biological aspects of environmental change, including climate change (LS8_5)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_6', 'Evolutionary ecology', 'Evolutionary ecology (LS8_6)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_7', 'Evolutionary genetics', 'Evolutionary genetics (LS8_7)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_8', 'Phylogenetics, systematics, comparative biology', 'Phylogenetics, systematics, comparative biology (LS8_8)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_9', 'Macroevolution and paleobiology', 'Macroevolution and paleobiology (LS8_9)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_10', 'Ecology and evolution of species interactions', 'Ecology and evolution of species interactions (LS8_10)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_11', 'Behavioural ecology and evolution', 'Behavioural ecology and evolution (LS8_11)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_12', 'Microbial ecology and evolution', 'Microbial ecology and evolution (LS8_12)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_13', 'Marine biology and ecology', 'Marine biology and ecology (LS8_13)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_14', 'Ecophysiology, from organisms to ecosystems', 'Ecophysiology, from organisms to ecosystems (LS8_14)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS8_15', 'Theoretical developments and modelling in environmental biology, ecology, and evolution', 'Theoretical developments and modelling in environmental biology, ecology, and evolution (LS8_15)', (SELECT id FROM research_domain WHERE key='LS8')),
	('LS9_1', 'Bioengineering for synthetic and chemical biology', 'Bioengineering for synthetic and chemical biology (LS9_1)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_2', 'Applied genetics, gene editing and transgenic organisms', 'Applied genetics, gene editing and transgenic organisms (LS9_2)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_3', 'Bioengineering of cells, tissues, organs and organisms', 'Bioengineering of cells, tissues, organs and organisms (LS9_3)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_4', 'Microbial biotechnology and bioengineering', 'Microbial biotechnology and bioengineering (LS9_4)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_5', 'Food biotechnology and bioengineering', 'Food biotechnology and bioengineering (LS9_5)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_6', 'Marine biotechnology and bioengineering', 'Marine biotechnology and bioengineering (LS9_6)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_7', 'Environmental biotechnology and bioengineering', 'Environmental biotechnology and bioengineering (LS9_7)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_8', 'Applied plant sciences, plant breeding, agroecology and soil biology', 'Applied plant sciences, plant breeding, agroecology and soil biology (LS9_8)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_9', 'Plant pathology and pest resistance', 'Plant pathology and pest resistance (LS9_9)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_10', 'Veterinary and applied animal sciences', 'Veterinary and applied animal sciences (LS9_10)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_11', 'Biomass production and utilisation, biofuels', 'Biomass production and utilisation, biofuels (LS9_11)', (SELECT id FROM research_domain WHERE key='LS9')),
	('LS9_12', 'Ecotoxicology, biohazards and biosafety', 'Ecotoxicology, biohazards and biosafety (LS9_12)', (SELECT id FROM research_domain WHERE key='LS9')),
	('SH1_1', 'Macroeconomics; monetary economics; economic growth', 'Macroeconomics; monetary economics; economic growth (SH1_1)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_2', 'International trade; international management; international business; spatial economics', 'International trade; international management; international business; spatial economics (SH1_2)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_3', 'Development economics; structural change; political economy of development', 'Development economics; structural change; political economy of development (SH1_3)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_4', 'Finance; asset pricing; international finance; market microstructure', 'Finance; asset pricing; international finance; market microstructure (SH1_4)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_5', 'Corporate finance; banking and financial intermediation; accounting; auditing; insurance', 'Corporate finance; banking and financial intermediation; accounting; auditing; insurance (SH1_5)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_6', 'Econometrics; operations research', 'Econometrics; operations research (SH1_6)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_7', 'Behavioural economics; experimental economics; neuro-economics', 'Behavioural economics; experimental economics; neuro-economics (SH1_7)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_8', 'Microeconomic theory; game theory; decision theory', 'Microeconomic theory; game theory; decision theory (SH1_8)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_9', 'Industrial organisation; entrepreneurship; R&D and innovation', 'Industrial organisation; entrepreneurship; R&D and innovation (SH1_9)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_10', 'Management; strategy; organisational behaviour', 'Management; strategy; organisational behaviour (SH1_10)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_11', 'Human resource management; operations management, marketing', 'Human resource management; operations management, marketing (SH1_11)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_12', 'Environmental economics; resource and energy economics; agricultural economics', 'Environmental economics; resource and energy economics; agricultural economics (SH1_12)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_13', 'Labour and demographic economics', 'Labour and demographic economics (SH1_13)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_14', 'Health economics; economics of education', 'Health economics; economics of education (SH1_14)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_15', 'Public economics; political economics; law and economics', 'Public economics; political economics; law and economics (SH1_15)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH1_16', 'Historical economics; quantitative economic history; institutional economics; economic systems', 'Historical economics; quantitative economic history; institutional economics; economic systems (SH1_16)', (SELECT id FROM research_domain WHERE key='SH1')),
	('SH2_1', 'Political systems, governance', 'Political systems, governance (SH2_1)', (SELECT id FROM research_domain WHERE key='SH2')),
	('SH2_2', 'Democratisation and social movements', 'Democratisation and social movements (SH2_2)', (SELECT id FROM research_domain WHERE key='SH2')),
	('SH2_3', 'Conflict resolution, war, peace building, international law', 'Conflict resolution, war, peace building, international law (SH2_3)', (SELECT id FROM research_domain WHERE key='SH2')),
	('SH2_4', 'Legal studies, constitutions, human rights, comparative law', 'Legal studies, constitutions, human rights, comparative law (SH2_4)', (SELECT id FROM research_domain WHERE key='SH2')),
	('SH2_5', 'International relations, global and transnational governance', 'International relations, global and transnational governance (SH2_5)', (SELECT id FROM research_domain WHERE key='SH2')),
	('SH2_6', 'Humanitarian assistance and development', 'Humanitarian assistance and development (SH2_6)', (SELECT id FROM research_domain WHERE key='SH2')),
	('SH2_7', 'Political and legal philosophy', 'Political and legal philosophy (SH2_7)', (SELECT id FROM research_domain WHERE key='SH2')),
	('SH2_8', 'Big data in political and legal studies', 'Big data in political and legal studies (SH2_8)', (SELECT id FROM research_domain WHERE key='SH2')),
	('SH3_1', 'Social structure, social mobility, social innovation', 'Social structure, social mobility, social innovation (SH3_1)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_2', 'Inequalities, discrimination, prejudice', 'Inequalities, discrimination, prejudice (SH3_2)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_3', 'Aggression and violence, antisocial behaviour, crime', 'Aggression and violence, antisocial behaviour, crime (SH3_3)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_4', 'Social integration, exclusion, prosocial behaviour', 'Social integration, exclusion, prosocial behaviour (SH3_4)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_5', 'Attitudes and beliefs', 'Attitudes and beliefs (SH3_5)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_6', 'Social influence; power and group behaviour', 'Social influence; power and group behaviour (SH3_6)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_7', 'Kinship; diversity and identities, gender, interethnic relations', 'Kinship; diversity and identities, gender, interethnic relations (SH3_7)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_8', 'Social policies, welfare, work and employment', 'Social policies, welfare, work and employment (SH3_8)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_9', 'Poverty and poverty alleviation', 'Poverty and poverty alleviation (SH3_9)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_10', 'Religious studies, ritual; symbolic representation', 'Religious studies, ritual; symbolic representation (SH3_10)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_11', 'Social aspects of teaching and learning, curriculum studies, education and educational policies', 'Social aspects of teaching and learning, curriculum studies, education and educational policies (SH3_11)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_12', 'Communication and information, networks, media', 'Communication and information, networks, media (SH3_12)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_13', 'Digital social research', 'Digital social research (SH3_13)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH3_14', 'Social studies of science and technology', 'Social studies of science and technology (SH3_14)', (SELECT id FROM research_domain WHERE key='SH3')),
	('SH4_1', 'Cognitive basis of human development and education, developmental disorders; comparative cognition', 'Cognitive basis of human development and education, developmental disorders; comparative cognition (SH4_1)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_2', 'Personality and social cognition; emotion', 'Personality and social cognition; emotion (SH4_2)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_3', 'Clinical and health psychology', 'Clinical and health psychology (SH4_3)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_4', 'Neuropsychology', 'Neuropsychology (SH4_4)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_5', 'Attention, perception, action, consciousness', 'Attention, perception, action, consciousness (SH4_5)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_6', 'Learning, memory; cognition in ageing', 'Learning, memory; cognition in ageing (SH4_6)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_7', 'Reasoning, decision-making; intelligence', 'Reasoning, decision-making; intelligence (SH4_7)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_8', 'Language learning and processing (first and second languages)', 'Language learning and processing (first and second languages) (SH4_8)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_9', 'Theoretical linguistics; computational linguistics', 'Theoretical linguistics; computational linguistics (SH4_9)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_10', 'Language typology; historical linguistics', 'Language typology; historical linguistics (SH4_10)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_11', 'Pragmatics, sociolinguistics, linguistic anthropology, discourse analysis', 'Pragmatics, sociolinguistics, linguistic anthropology, discourse analysis (SH4_11)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_12', 'Philosophy of mind, philosophy of language', 'Philosophy of mind, philosophy of language (SH4_12)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH4_13', 'Philosophy of science, epistemology, logic', 'Philosophy of science, epistemology, logic (SH4_13)', (SELECT id FROM research_domain WHERE key='SH4')),
	('SH5_1', 'Classics, ancient literature and art', 'Classics, ancient literature and art (SH5_1)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_2', 'Theory and history of literature, comparative literature', 'Theory and history of literature, comparative literature (SH5_2)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_3', 'Philology; text and image studies', 'Philology; text and image studies (SH5_3)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_4', 'Visual and performing arts, film, design and architecture', 'Visual and performing arts, film, design and architecture (SH5_4)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_5', 'Music and musicology; history of music', 'Music and musicology; history of music (SH5_5)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_6', 'History of art and architecture, arts-based research', 'History of art and architecture, arts-based research (SH5_6)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_7', 'Museums, exhibitions, conservation and restoration', 'Museums, exhibitions, conservation and restoration (SH5_7)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_8', 'Cultural studies, cultural identities and memories, cultural heritage', 'Cultural studies, cultural identities and memories, cultural heritage (SH5_8)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_9', 'Metaphysics, philosophical anthropology; aesthetics', 'Metaphysics, philosophical anthropology; aesthetics (SH5_9)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_10', 'Ethics and its applications; social philosophy', 'Ethics and its applications; social philosophy (SH5_10)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_11', 'History of philosophy', 'History of philosophy (SH5_11)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH5_12', 'Computational modelling and digitisation in the cultural sphere', 'Computational modelling and digitisation in the cultural sphere (SH5_12)', (SELECT id FROM research_domain WHERE key='SH5')),
	('SH6_1', 'Historiography, theory and methods in history, including the analysis of digital data', 'Historiography, theory and methods in history, including the analysis of digital data (SH6_1)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_2', 'Classical archaeology, history of archaeology, social archaeology', 'Classical archaeology, history of archaeology, social archaeology (SH6_2)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_3', 'General archaeology, archaeometry, landscape archaeology', 'General archaeology, archaeometry, landscape archaeology (SH6_3)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_4', 'Prehistory, palaeoanthropology, palaeodemography, protohistory, bioarchaeology', 'Prehistory, palaeoanthropology, palaeodemography, protohistory, bioarchaeology (SH6_4)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_5', 'Palaeography and codicology', 'Palaeography and codicology (SH6_5)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_6', 'Ancient history', 'Ancient history (SH6_6)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_7', 'Medieval history', 'Medieval history (SH6_7)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_8', 'Early modern history', 'Early modern history (SH6_8)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_9', 'Modern and contemporary history', 'Modern and contemporary history (SH6_9)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_10', 'Colonial and post-colonial history', 'Colonial and post-colonial history (SH6_10)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_11', 'Global history, transnational history, comparative history, entangled histories', 'Global history, transnational history, comparative history, entangled histories (SH6_11)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_12', 'Social and economic history', 'Social and economic history (SH6_12)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_13', 'Gender history, cultural history, history of collective identities and memories, history of religions', 'Gender history, cultural history, history of collective identities and memories, history of religions (SH6_13)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_14', 'History of ideas, intellectual history, history of economic thought', 'History of ideas, intellectual history, history of economic thought (SH6_14)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH6_15', 'History of science, medicine and technologies', 'History of science, medicine and technologies (SH6_15)', (SELECT id FROM research_domain WHERE key='SH6')),
	('SH7_1', 'Human, economic and social geography', 'Human, economic and social geography (SH7_1)', (SELECT id FROM research_domain WHERE key='SH7')),
	('SH7_2', 'Migration', 'Migration (SH7_2)', (SELECT id FROM research_domain WHERE key='SH7')),
	('SH7_3', 'Population dynamics: households, family and fertility', 'Population dynamics: households, family and fertility (SH7_3)', (SELECT id FROM research_domain WHERE key='SH7')),
	('SH7_4', 'Social aspects of health, ageing and society', 'Social aspects of health, ageing and society (SH7_4)', (SELECT id FROM research_domain WHERE key='SH7')),
	('SH7_5', 'Sustainability sciences, environment and resources', 'Sustainability sciences, environment and resources (SH7_5)', (SELECT id FROM research_domain WHERE key='SH7')),
	('SH7_6', 'Environmental and climate change, societal impact and policy', 'Environmental and climate change, societal impact and policy (SH7_6)', (SELECT id FROM research_domain WHERE key='SH7')),
	('SH7_7', 'Cities; urban, regional and rural studies', 'Cities; urban, regional and rural studies (SH7_7)', (SELECT id FROM research_domain WHERE key='SH7')),
	('SH7_8', 'Land use and planning', 'Land use and planning (SH7_8)', (SELECT id FROM research_domain WHERE key='SH7')),
	('SH7_9', 'Energy, transportation and mobility', 'Energy, transportation and mobility (SH7_9)', (SELECT id FROM research_domain WHERE key='SH7')),
	('SH7_10', 'GIS, spatial analysis; big data in geographical studies', 'GIS, spatial analysis; big data in geographical studies (SH7_10)', (SELECT id FROM research_domain WHERE key='SH7'))
;
