// SPDX-FileCopyrightText: 2026 Dusan Mijatovic (Netherlands eScience Center)
// SPDX-FileCopyrightText: 2026 Netherlands eScience Center
//
// SPDX-License-Identifier: Apache-2.0

// Initially generated by local AI Qwen-coder-3.6:30b
// then adapted by Dusan to fix "errors"

import {render, screen, fireEvent} from '@testing-library/react'
import ConfirmDeleteModal from './ConfirmDeleteModal'

// Mock useSmallScreen hook
jest.mock('~/config/useSmallScreen', () => ({
  __esModule: true,
  default: jest.fn(() => false)
}))

it('renders the modal with correct title and warning icon', () => {
  const mockOnCancel = jest.fn()
  const mockOnDelete = jest.fn()

  render(
    <ConfirmDeleteModal
      open={true}
      title="Test Title"
      onCancel={mockOnCancel}
      onDelete={mockOnDelete}
    />
  )

  expect(screen.getByText('Test Title')).toBeInTheDocument()
  expect(screen.getByTestId('WarningIcon')).toBeInTheDocument()
})

it('renders the modal body content', () => {
  const mockOnCancel = jest.fn()
  const mockOnDelete = jest.fn()

  const bodyContent = <p>Test body content</p>
  render(
    <ConfirmDeleteModal
      open={true}
      body={bodyContent}
      onCancel={mockOnCancel}
      onDelete={mockOnDelete}
    />
  )

  expect(screen.getByText('Test body content')).toBeInTheDocument()
})

it('renders remove button with delete icon', () => {
  const mockOnCancel = jest.fn()
  const mockOnDelete = jest.fn()

  render(
    <ConfirmDeleteModal
      open={true}
      onCancel={mockOnCancel}
      onDelete={mockOnDelete}
    />
  )

  const removeButton = screen.getByRole('button', {name: 'Remove'})
  expect(removeButton).toBeInTheDocument()
  expect(screen.getByTestId('DeleteIcon')).toBeInTheDocument()
})

it('calls onDelete when remove button is clicked', () => {
  const mockOnCancel = jest.fn()
  const mockOnDelete = jest.fn()

  render(
    <ConfirmDeleteModal
      open={true}
      onCancel={mockOnCancel}
      onDelete={mockOnDelete}
    />
  )

  const removeButton = screen.getByRole('button', {name: 'Remove'})
  fireEvent.click(removeButton)

  expect(mockOnDelete).toHaveBeenCalledTimes(1)
})

it('calls onCancel when cancel button is clicked', () => {
  const mockOnCancel = jest.fn()
  const mockOnDelete = jest.fn()

  render(
    <ConfirmDeleteModal
      open={true}
      onCancel={mockOnCancel}
      onDelete={mockOnDelete}
    />
  )

  const cancelButton = screen.getByRole('button', {name: 'Cancel'})
  fireEvent.click(cancelButton)

  expect(mockOnCancel).toHaveBeenCalledTimes(1)
})

it('disables remove button when removeDisabled is true', () => {
  const mockOnCancel = jest.fn()
  const mockOnDelete = jest.fn()

  render(
    <ConfirmDeleteModal
      open={true}
      onCancel={mockOnCancel}
      onDelete={mockOnDelete}
      removeDisabled={true}
    />
  )

  const removeButton = screen.getByRole('button', {name: 'Remove'})
  expect(removeButton).toBeDisabled()
})

it('enables remove button when removeDisabled is false', () => {
  const mockOnCancel = jest.fn()
  const mockOnDelete = jest.fn()

  render(
    <ConfirmDeleteModal
      open={true}
      onCancel={mockOnCancel}
      onDelete={mockOnDelete}
      removeDisabled={false}
    />
  )

  const removeButton = screen.getByRole('button', {name: 'Remove'})
  expect(removeButton).not.toBeDisabled()
})

it('renders with fullScreen on small screens when useSmallScreen returns true', () => {
  // Mock useSmallScreen to return true
  jest.mock('~/config/useSmallScreen', () => ({
    __esModule: true,
    default: jest.fn(() => true)
  }))

  const mockOnCancel = jest.fn()
  const mockOnDelete = jest.fn()

  render(
    <ConfirmDeleteModal
      open={true}
      onCancel={mockOnCancel}
      onDelete={mockOnDelete}
    />
  )

  // Check that the modal is rendered with fullScreen prop
  expect(screen.getByTestId('confirm-delete-modal')).toBeInTheDocument()
})

it('renders correctly when open is false', () => {
  const mockOnCancel = jest.fn()
  const mockOnDelete = jest.fn()

  render(
    <ConfirmDeleteModal
      open={false}
      onCancel={mockOnCancel}
      onDelete={mockOnDelete}
    />
  )

  // The modal should not be visible
  expect(screen.queryByTestId('confirm-delete-modal')).not.toBeInTheDocument()
})

it('renders with default title when no title is provided', () => {
  const mockOnCancel = jest.fn()
  const mockOnDelete = jest.fn()

  render(
    <ConfirmDeleteModal
      open={true}
      onCancel={mockOnCancel}
      onDelete={mockOnDelete}
    />
  )

  expect(screen.getByRole('heading',{name: 'Remove'})).toBeInTheDocument()
})
