# SPDX-FileCopyrightText: 2021 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2021 Netherlands eScience Center
#
# SPDX-License-Identifier: Apache-2.0

FROM postgrest/postgrest:v9.0.0
