// SPDX-FileCopyrightText: 2026 Dusan Mijatovic (Netherlands eScience Center)
// SPDX-FileCopyrightText: 2026 Netherlands eScience Center
//
// SPDX-License-Identifier: Apache-2.0

/**
 * Test generated by Google AI Mode based on the component code!
 * Slightly adjusted by Dusan to work as expected :-)
*/

import logger from '~/utils/logger'
import {
  getSoftwareList,
  getSoftwareItem,
  getReleasesForSoftware,
  getKeywordsForSoftware,
  getCategoriesForSoftware,
  getCategoryForSoftwareIds,
  addCategoryToSoftware,
  deleteCategoryToSoftware,
  getLicenseForSoftware,
  getBadgesForSoftware,
  addBadgeForSoftware,
  deleteBadge,
  updateBadgeContent,
  updateBadgePosition
} from './apiSoftware'

// 1. Mock your custom local utilities to avoid runtime issues
jest.mock('~/utils/logger', () => jest.fn())
jest.mock('~/utils/extractCountFromHeader', () => ({
  extractCountFromHeader: () => 15
}))
jest.mock('~/utils/fetchHelpers', () => ({
  createJsonHeaders: (token?: string) => ({
    'Content-Type': 'application/json',
    ...(token ? {Authorization: `Bearer ${token}`} : {})
  }),
  getBaseUrl: () => 'https://test-domain.com'
}))

let fetchSpy: jest.SpyInstance

beforeEach(() => {
  jest.clearAllMocks()
  fetchSpy = jest.spyOn(global, 'fetch')
})

afterEach(() => {
  fetchSpy.mockRestore()
})

it('getSoftwareList: attaches security token correctly to authorization headers', async () => {
  fetchSpy.mockResolvedValueOnce({
    status: 200,
    headers: new Headers(),
    json: async () => [],
  } as Response)

  await getSoftwareList({url: 'https://test-domain.com/software', token: 'secret-jwt-token'})

  expect(fetchSpy).toHaveBeenCalledWith(
    'https://test-domain.com/software',
    expect.objectContaining({
      headers: expect.objectContaining({
        Authorization: 'Bearer secret-jwt-token',
        'Prefer': 'count=exact'
      })
    })
  )
})

it('getSoftwareItem: forwards authentication tokens correctly down to individual slug calls', async () => {
  fetchSpy.mockResolvedValueOnce({
    status: 200,
    json: async () => [{}],
  } as Response)

  await getSoftwareItem({slug: 'target-slug', token: 'user-session-token'})

  expect(fetchSpy).toHaveBeenCalledWith(
    'https://test-domain.com/software?slug=eq.target-slug',
    expect.objectContaining({
      headers: expect.objectContaining({
        Authorization: 'Bearer user-session-token'
      })
    })
  )
})

it('getReleasesForSoftware: carries optional token structures seamlessly to release pathways', async () => {
  fetchSpy.mockResolvedValueOnce({
    status: 200,
    json: async () => [],
  } as Response)

  await getReleasesForSoftware('uuid-999', 'secure-badge-token')

  expect(fetchSpy).toHaveBeenCalledWith(
    expect.stringContaining('uuid-999'),
    expect.objectContaining({
      headers: expect.objectContaining({
        Authorization: 'Bearer secure-badge-token'
      })
    })
  )
})

it('getSoftwareList: returns formatted data and structural counts on successful status code combinations', async () => {
  const mockPayload = [{id: '1', name: 'App A'}]

  fetchSpy.mockResolvedValueOnce({
    status: 206,
    headers: new Headers(),
    json: async () => mockPayload,
  } as Response)

  const result = await getSoftwareList({url: 'https://test-domain.com/software'})

  expect(result).toEqual({count: 15, data: mockPayload})
})

it('getSoftwareList: returns default fallback object parameters if status validation fails', async () => {
  fetchSpy.mockResolvedValueOnce({
    status: 500,
    statusText: 'Internal Server Error',
  } as Response)

  const result = await getSoftwareList({url: 'https://test-domain.com/software'})

  expect(result).toEqual({count: 0, data: []})
  expect(logger).toHaveBeenCalledWith(expect.stringContaining('getSoftwareList failed: 500'), 'warn')
})

it('getSoftwareItem: extracts index element from standard item query responses', async () => {
  const mockRecord = {slug: 'target-slug', name: 'Software Item'}

  fetchSpy.mockResolvedValueOnce({
    status: 200,
    json: async () => [mockRecord],
  } as Response)

  const result = await getSoftwareItem({slug: 'target-slug'})
  expect(result).toEqual(mockRecord)
})

it('getReleasesForSoftware: safely walks deep nested release property structures', async () => {
  const compoundPayload = [
    {
      release: {
        mention: [{doi: '10.abc/1', version: '2.1.0', doi_registration_date: '2026-03-12'}]
      }
    }
  ]

  fetchSpy.mockResolvedValueOnce({
    status: 200,
    json: async () => compoundPayload,
  } as Response)

  const result = await getReleasesForSoftware('uuid-999')
  expect(result).toEqual([{doi: '10.abc/1', version: '2.1.0', doi_registration_date: '2026-03-12'}])
})

it('getReleasesForSoftware: returns null safely without throwing if data arrays are structured incorrectly', async () => {
  fetchSpy.mockResolvedValueOnce({
    status: 200,
    json: async () => [{}],
  } as Response)

  const result = await getReleasesForSoftware('uuid-malformed')
  expect(result).toBeNull()
})

it('getKeywordsForSoftware: returns array of keywords on successful status 200', async () => {
  const mockKeywords = [{id: 'k1', keyword: 'React'}]
  fetchSpy.mockResolvedValueOnce({
    status: 200,
    json: async () => mockKeywords,
  } as Response)

  const result = await getKeywordsForSoftware('uuid-123')
  expect(result).toEqual(mockKeywords)
  expect(fetchSpy).toHaveBeenCalledWith(expect.stringContaining('rpc/keywords_by_software'), expect.any(Object))
})

it('getKeywordsForSoftware: catches 404 response errors dynamically and falls back safely', async () => {
  fetchSpy.mockResolvedValueOnce({status: 404} as Response)

  const result = await getKeywordsForSoftware('uuid-missing')
  expect(result).toBeNull()
  expect(logger).toHaveBeenCalledWith(expect.stringContaining('getKeywordsForSoftware: 404'), 'error')
})

it('getCategoriesForSoftware: maps path parameters correctly and processes paths arrays on success', async () => {
  const mockCategories = [{category_id: 'c1'}]
  fetchSpy.mockResolvedValueOnce({
    status: 200,
    json: async () => mockCategories,
  } as Response)

  const result = await getCategoriesForSoftware('soft-123')
  expect(result).toEqual(mockCategories)
  expect(fetchSpy).toHaveBeenCalledWith(
    'https://test-domain.com/rpc/category_paths_by_software_expanded?software_id=soft-123',
    expect.any(Object)
  )
})

it('getCategoryForSoftwareIds: transforms parsed arrays directly into ES6 Set maps on 200 response states', async () => {
  fetchSpy.mockResolvedValueOnce({
    status: 200,
    json: async () => [{category_id: 'id-a'}, {category_id: 'id-b'}],
  } as Response)

  const result = await getCategoryForSoftwareIds('soft-123')
  expect(result).toBeInstanceOf(Set)
  expect(result.has('id-a')).toBe(true)
  expect(result.has('id-b')).toBe(true)
})

it('getCategoryForSoftwareIds: captures failures and throws unique explicit instances', async () => {
  fetchSpy.mockResolvedValueOnce({status: 404} as Response)

  await expect(getCategoryForSoftwareIds('soft-invalid')).rejects.toThrow(
    'Couldn\'t find the categories for this software'
  )
})

it('addCategoryToSoftware: encodes payloads as stringified body content and resolves cleanly on ok', async () => {
  fetchSpy.mockResolvedValueOnce({ok: true} as Response)

  const result = await addCategoryToSoftware('soft-123', 'cat-999', 'token-abc')

  expect(result).toBeNull()
  expect(fetchSpy).toHaveBeenCalledWith(
    'https://test-domain.com/category_for_software',
    expect.objectContaining({
      method: 'POST',
      body: JSON.stringify({software_id: 'soft-123', category_id: 'cat-999'})
    })
  )
})

it('addCategoryToSoftware: throws errors explicitly if server payload response is not ok', async () => {
  fetchSpy.mockResolvedValueOnce({ok: false, status: 400, statusText: 'Bad Request'} as Response)

  await expect(addCategoryToSoftware('soft-123', 'cat-999', 'token-abc')).rejects.toThrow(
    'API returned: 400 Bad Request'
  )
})

it('deleteCategoryToSoftware: formats query strings correctly on raw target deletion steps', async () => {
  fetchSpy.mockResolvedValueOnce({ok: true} as Response)

  const result = await deleteCategoryToSoftware('soft-123', 'cat-456', 'token-xyz')

  expect(result).toBeNull()
  expect(fetchSpy).toHaveBeenCalledWith(
    'https://test-domain.com/category_for_software?software_id=eq.soft-123&category_id=eq.cat-456',
    expect.objectContaining({method: 'DELETE'})
  )
})

it('getLicenseForSoftware: extracts full payload arrays on successful data iterations', async () => {
  const mockLicenses = [{license: 'MIT'}]
  fetchSpy.mockResolvedValueOnce({
    status: 200,
    json: async () => mockLicenses,
  } as Response)

  const result = await getLicenseForSoftware('soft-123')
  expect(result).toEqual(mockLicenses)
})

it('getSoftwareList: returns default fallback object parameters if status validation fails', async () => {
  fetchSpy.mockResolvedValueOnce({status: 500, statusText: 'Internal Server Error'} as Response)
  const result = await getSoftwareList({url: 'https://test-domain.com/software'})
  expect(result).toEqual({count: 0, data: []})
})

it('getSoftwareItem: extracts index element from standard item query responses', async () => {
  const mockRecord = {slug: 'target-slug', name: 'Software Item'}
  fetchSpy.mockResolvedValueOnce({status: 200, json: async () => [mockRecord]} as Response)
  const result = await getSoftwareItem({slug: 'target-slug'})
  expect(result).toEqual(mockRecord)
})

it('getReleasesForSoftware: safely walks deep nested release property structures', async () => {
  const compoundPayload = [{release: {mention: [{doi: '10.abc/1', version: '2.1.0'}]}}]
  fetchSpy.mockResolvedValueOnce({status: 200, json: async () => compoundPayload} as Response)
  const result = await getReleasesForSoftware('uuid-999')
  expect(result).toEqual([{doi: '10.abc/1', version: '2.1.0'}])
})

it('getReleasesForSoftware: returns null safely without throwing if status is 404', async () => {
  fetchSpy.mockResolvedValueOnce({status: 404} as Response)
  const result = await getReleasesForSoftware('uuid-missing')
  expect(result).toBeNull()
})

it('getKeywordsForSoftware: returns array of keywords on successful status 200', async () => {
  const mockKeywords = [{id: 'k1', keyword: 'React'}]
  fetchSpy.mockResolvedValueOnce({status: 200, json: async () => mockKeywords} as Response)
  const result = await getKeywordsForSoftware('uuid-123')
  expect(result).toEqual(mockKeywords)
})

it('getKeywordsForSoftware: catches 404 response errors dynamically and falls back safely', async () => {
  fetchSpy.mockResolvedValueOnce({status: 404} as Response)
  const result = await getKeywordsForSoftware('uuid-missing')
  expect(result).toBeNull()
})

it('getCategoriesForSoftware: maps path parameters correctly and processes paths arrays on success', async () => {
  const mockCategories = [{category_id: 'c1'}]
  fetchSpy.mockResolvedValueOnce({status: 200, json: async () => mockCategories} as Response)
  const result = await getCategoriesForSoftware('soft-123')
  expect(result).toEqual(mockCategories)
})

it('getCategoryForSoftwareIds: transforms parsed arrays directly into ES6 Set maps on 200 response states', async () => {
  fetchSpy.mockResolvedValueOnce({status: 200, json: async () => [{category_id: 'id-a'}]} as Response)
  const result = await getCategoryForSoftwareIds('soft-123')
  expect(result.has('id-a')).toBe(true)
})

it('getCategoryForSoftwareIds: captures failures and throws unique explicit instances', async () => {
  fetchSpy.mockResolvedValueOnce({status: 404} as Response)
  await expect(getCategoryForSoftwareIds('soft-invalid')).rejects.toThrow()
})

it('addCategoryToSoftware: encodes payloads as stringified body content and resolves cleanly on ok', async () => {
  fetchSpy.mockResolvedValueOnce({ok: true} as Response)
  const result = await addCategoryToSoftware('soft-123', 'cat-999', 'token-abc')
  expect(result).toBeNull()
})

it('addCategoryToSoftware: throws errors explicitly if server payload response is not ok', async () => {
  fetchSpy.mockResolvedValueOnce({ok: false, status: 400, statusText: 'Bad Request'} as Response)
  await expect(addCategoryToSoftware('soft-123', 'cat-999', 'token-abc')).rejects.toThrow()
})

it('deleteCategoryToSoftware: formats query strings correctly on raw target deletion steps', async () => {
  fetchSpy.mockResolvedValueOnce({ok: true} as Response)
  const result = await deleteCategoryToSoftware('soft-123', 'cat-456', 'token-xyz')
  expect(result).toBeNull()
})

it('deleteCategoryToSoftware: throws error if delete response is not ok', async () => {
  fetchSpy.mockResolvedValueOnce({ok: false, status: 401, statusText: 'Unauthorized'} as Response)
  await expect(deleteCategoryToSoftware('soft-123', 'cat-456', 'token-xyz')).rejects.toThrow()
})

it('getLicenseForSoftware: extracts full payload arrays on successful data iterations', async () => {
  const mockLicenses = [{license: 'MIT'}]
  fetchSpy.mockResolvedValueOnce({status: 200, json: async () => mockLicenses} as Response)
  const result = await getLicenseForSoftware('soft-123')
  expect(result).toEqual(mockLicenses)
})

it('getLicenseForSoftware: handles 404 or catch blocks elegantly by returning an empty array', async () => {
  fetchSpy.mockResolvedValueOnce({status: 404} as Response)
  const result = await getLicenseForSoftware('soft-none')
  expect(result).toEqual([])
})

// === MISSING FUNCTIONS COVERAGE TARGETING LINES 249 - 531 ===

it('getBadgesForSoftware: fetches badges matching software identification requirements sorted by position', async () => {
  const mockBadges = [{id: 'b1', position: 1}]
  fetchSpy.mockResolvedValueOnce({ok: true, json: async () => mockBadges} as Response)

  const result = await getBadgesForSoftware('soft-123', 'token-abc')

  expect(fetchSpy).toHaveBeenCalledWith(
    'https://test-domain.com/badge?&software=eq.soft-123&order=position.asc',
    expect.any(Object)
  )
  expect(result).toEqual(mockBadges)
})

it('getBadgesForSoftware: returns empty array fallback parameters if endpoint throws a 404 error', async () => {
  fetchSpy.mockResolvedValueOnce({ok: false, status: 404} as Response)
  const result = await getBadgesForSoftware('soft-missing')
  expect(result).toEqual([])
})

it('addBadgeForSoftware: creates new badge using POST operations containing positional fields', async () => {
  fetchSpy.mockResolvedValueOnce({ok: true} as Response)

  await addBadgeForSoftware('token-123', {
    softwareId: 'soft-123',
    badgeUrl: 'https://img.url',
    altText: 'Alt',
    badgeLink: 'https://link.url',
    position: 1
  })

  expect(fetchSpy).toHaveBeenCalledWith(
    expect.stringContaining('/badge'),
    expect.objectContaining({method: 'POST'})
  )
})

it('deleteBadge: sends programmatic DELETE validation calls targeting direct item IDs', async () => {
  fetchSpy.mockResolvedValueOnce({ok: true} as Response)

  await deleteBadge('token-123', 'badge-id-999')

  expect(fetchSpy).toHaveBeenCalledWith(
    expect.stringContaining('id=eq.badge-id-999'),
    expect.objectContaining({method: 'DELETE'})
  )
})

it('updateBadgeContent: triggers PATCH operations passing structured changes down payload structures', async () => {
  fetchSpy.mockResolvedValueOnce({ok: true} as Response)

  await updateBadgeContent('token-123', {
    badgeId: 'badge-777',
    badgeUrl: 'https://new.url',
    altText: 'New Alt',
    badgeLink: 'https://new.link'
  })

  expect(fetchSpy).toHaveBeenCalledWith(
    expect.stringContaining('id=eq.badge-777'),
    expect.objectContaining({method: 'PATCH'})
  )
})

it('updateBadgePosition: updates ordering properties asynchronously across internal collection entries', async () => {
  fetchSpy.mockResolvedValueOnce({ok: true} as Response)

  await updateBadgePosition('token-123', 'badge-444', 5)

  expect(fetchSpy).toHaveBeenCalledWith(
    expect.stringContaining('id=eq.badge-444'),
    expect.objectContaining({
      method: 'PATCH',
      body: JSON.stringify({position: 5})
    })
  )
})
