// SPDX-FileCopyrightText: 2026 Dusan Mijatovic (Netherlands eScience Center)
// SPDX-FileCopyrightText: 2026 Netherlands eScience Center
//
// SPDX-License-Identifier: Apache-2.0

/**
 * Test generated by Google AI Mode based on the component code!
 * Slightly adjusted by Dusan to work as expected :-)
*/
import {screen, render, waitFor, fireEvent, act} from '@testing-library/react'
import {useAsyncFieldValidation} from '~/components/form/useAsyncFieldValidation'
import EditSoftwareBadgeModal from './EditSoftwareBadgeModal'

// 1. Mock external utility functions and custom hooks
jest.mock('~/utils/validateImageSrc', () => jest.fn())
jest.mock('~/config/useSmallScreen', () => () => false)

// 2. Mock useAsyncFieldValidation to easily toggle loading states dynamically
jest.mock('~/components/form/useAsyncFieldValidation', () => ({
  useAsyncFieldValidation: jest.fn().mockReturnValue({isValidating: false})
}))

const mockUseAsyncFieldValidation = useAsyncFieldValidation as jest.Mock

// 3. Mock the configuration descriptors to supply the mock execution closure
jest.mock('~/components/software/edit/links/config', () => ({
  config: {
    badges: {
      badgeUrl: {
        label: 'Badge URL',
        help: 'Enter image link',
        validation: ({existingBadgeUrls, ignoreUrl}: any) => ({
          maxLength: {value: 100},
          validate: {
            duplicateBadge: (value: string) => {
              if (existingBadgeUrls.has(value) && value !== ignoreUrl) {
                return 'This badge already exists for this software'
              }
            }
          }
        })
      },
      altText: {label: 'Alt Text', help: 'Enter text', validation: {maxLength: {value: 100}}},
      badgeLink: {label: 'Badge Link', help: 'Enter target link', validation: {maxLength: {value: 100}}},
    }
  }
}))

const mockOnSave = jest.fn()
const mockOnCancel = jest.fn()
const mockExistingUrls = new Set(['https://example.com'])

beforeEach(() => {
  jest.useFakeTimers()
  jest.clearAllMocks()
})

afterEach(() => {
  jest.useRealTimers()
})

it('renders correctly in "Add badge" mode when no badge data is provided', () => {
  render(
    <EditSoftwareBadgeModal
      existingBadgeUrls={mockExistingUrls}
      onSave={mockOnSave}
      onCancel={mockOnCancel}
    />
  )

  expect(screen.getByRole('heading', {name: 'Add badge'})).toBeInTheDocument()
  expect(screen.getByLabelText('Badge URL')).toBeInTheDocument()
  expect(screen.getByRole('button', {name: 'Save'})).toBeDisabled()
})

it('calls onCancel when the cancel button is clicked', () => {
  render(
    <EditSoftwareBadgeModal
      existingBadgeUrls={mockExistingUrls}
      onSave={mockOnSave}
      onCancel={mockOnCancel}
    />
  )

  const cancelButton = screen.getByRole('button', {name: 'Cancel'})
  fireEvent.click(cancelButton)
  expect(mockOnCancel).toHaveBeenCalledTimes(1)
})

it('submits successfully if form fields are valid and hook is not loading', async () => {
  render(
    <EditSoftwareBadgeModal
      existingBadgeUrls={mockExistingUrls}
      onSave={mockOnSave}
      onCancel={mockOnCancel}
    />
  )

  const urlInput = screen.getByLabelText('Badge URL')
  const saveButton = screen.getByRole('button', {name: 'Save'})
  const bageUrl = 'https://shields.io'

  fireEvent.change(urlInput, {target: {value: bageUrl}})

  await waitFor(() => {
    expect(saveButton).not.toBeDisabled()
  })

  fireEvent.click(saveButton)

  await waitFor(() => {
    expect(mockOnSave).toHaveBeenCalled()
    expect(mockOnSave).toHaveBeenCalledWith(
      expect.objectContaining({
        badgeUrl: bageUrl
      }),
      expect.any(Object)
    )
  })
})

it('shows an error message if the user enters a duplicate badge URL', async () => {
  render(
    <EditSoftwareBadgeModal
      existingBadgeUrls={mockExistingUrls}
      onSave={mockOnSave}
      onCancel={mockOnCancel}
    />
  )

  const urlInput = screen.getByLabelText('Badge URL')
  fireEvent.change(urlInput, {target: {value: 'https://example.com'}})

  await waitFor(() => {
    expect(screen.getByText('This badge already exists for this software')).toBeInTheDocument()
  })

  expect(screen.getByRole('button', {name: 'Save'})).toBeDisabled()
})

it('displays a spinner and disables the save button while async background validation is running', async () => {
  // Simulate active background computation inside our custom hook runtime
  mockUseAsyncFieldValidation.mockReturnValue({isValidating: true})

  render(
    <EditSoftwareBadgeModal
      existingBadgeUrls={mockExistingUrls}
      onSave={mockOnSave}
      onCancel={mockOnCancel}
    />
  )

  const urlInput = screen.getByLabelText('Badge URL')
  fireEvent.change(urlInput, {target: {value: 'https://shields.io'}})

  await act(async () => {
    await Promise.resolve()
  })

  // Assert that Material UI's CircularProgress indicator registers visible in the layout tree
  expect(screen.getByRole('progressbar')).toBeInTheDocument()
  expect(screen.getByRole('button', {name: 'Save'})).toBeDisabled()
})
