// SPDX-FileCopyrightText: 2026 Dusan Mijatovic (Netherlands eScience Center)
// SPDX-FileCopyrightText: 2026 Netherlands eScience Center
//
// SPDX-License-Identifier: Apache-2.0

/**
 * Test generated by Google AI Mode based on the component code!
 * Sligthly adjusted by Dusan to work as expected :-)
*/
import {screen, render, waitFor, fireEvent, act} from '@testing-library/react'
import EditSoftwareBadgeModal from './EditSoftwareBadgeModal'
import validateImageSrc from '~/utils/validateImageSrc'

// 1. Mock external utility functions
jest.mock('~/utils/validateImageSrc', () => jest.fn())
jest.mock('~/config/useSmallScreen', () => () => false)

// 2. Mock the configuration descriptions
jest.mock('~/components/software/edit/links/config', () => ({
  config: {
    badges: {
      badgeUrl: {label: 'Badge URL', help: 'Enter image link', validation: {maxLength: {value: 100}}},
      altText: {label: 'Alt Text', help: 'Enter text', validation: {maxLength: {value: 100}}},
      badgeLink: {label: 'Badge Link', help: 'Enter target link', validation: {maxLength: {value: 100}}},
    }
  }
}))

const mockOnSave = jest.fn()
const mockOnCancel = jest.fn()
const mockExistingUrls = new Set(['https://example.com'])

beforeEach(() => {
  jest.useFakeTimers()
  jest.clearAllMocks()
  ;(validateImageSrc as jest.Mock).mockResolvedValue(true)
})

afterEach(() => {
  jest.useRealTimers()
})

it('renders correctly in "Add badge" mode when no badge data is provided', () => {
  render(
    <EditSoftwareBadgeModal
      existingBadgeUrls={mockExistingUrls}
      onSave={mockOnSave}
      onCancel={mockOnCancel}
    />
  )

  expect(screen.getByRole('heading', {name: 'Add badge'})).toBeInTheDocument()
  expect(screen.getByLabelText('Badge URL')).toBeInTheDocument()
  expect(screen.getByRole('button', {name: 'Save'})).toBeDisabled()
})

it('calls onCancel when the cancel button is clicked', () => {
  render(
    <EditSoftwareBadgeModal
      existingBadgeUrls={mockExistingUrls}
      onSave={mockOnSave}
      onCancel={mockOnCancel}
    />
  )

  const cancelButton = screen.getByRole('button', {name: 'Cancel'})

  // Replaced userEvent with synchronous fireEvent
  fireEvent.click(cancelButton)

  expect(mockOnCancel).toHaveBeenCalledTimes(1)
})

it('triggers debounced form validation and submits successfully if data is valid', async () => {
  render(
    <EditSoftwareBadgeModal
      existingBadgeUrls={mockExistingUrls}
      onSave={mockOnSave}
      onCancel={mockOnCancel}
    />
  )

  const urlInput = screen.getByLabelText('Badge URL')
  const saveButton = screen.getByRole('button', {name: 'Save'})
  const bageUrl = 'https://shields.io'

  // 1. Simulate typing the new value
  fireEvent.change(urlInput, {target: {value: bageUrl}})

  // 2. Step inside an async act block to flush react-hook-form's validator object chain
  await act(async () => {
    // Flush the initial microtask queue so react-hook-form schedules the debounce setTimeout
    await Promise.resolve()

    // Now that the timeout is scheduled, advance the fake timer safely
    jest.advanceTimersByTime(500)

    // Flush the final microtask queue so the resolved validateImageSrc mock applies
    await Promise.resolve()
  })

  // 3. Wait for the form state to finish updating and unlock the button
  await waitFor(() => {
    expect(saveButton).not.toBeDisabled()
  })

  // 4. Submit the form
  fireEvent.click(saveButton)

  await waitFor(() => {
    expect(mockOnSave).toHaveBeenCalled()
    expect(mockOnSave).toHaveBeenCalledWith(
      expect.objectContaining({
        badgeUrl: bageUrl
      }),
      // Ignore form submit event object (second argument)
      expect.any(Object)
    )
  })
})

it('shows an error message if the user enters a duplicate badge URL', async () => {
  render(
    <EditSoftwareBadgeModal
      existingBadgeUrls={mockExistingUrls}
      onSave={mockOnSave}
      onCancel={mockOnCancel}
    />
  )

  const urlInput = screen.getByLabelText('Badge URL')

  // Simulate inputting the URL that already exists in the Set
  fireEvent.change(urlInput, {target: {value: 'https://example.com'}})

  // Fast forward debounce timer
  jest.advanceTimersByTime(500)

  // The component should display the error message populated into helperTextMessage
  await waitFor(() => {
    expect(screen.getByText('This badge already exists for this software')).toBeInTheDocument()
  })

  expect(screen.getByRole('button', {name: 'Save'})).toBeDisabled()
})

