// SPDX-FileCopyrightText: 2026 Dusan Mijatovic (Netherlands eScience Center)
// SPDX-FileCopyrightText: 2026 Netherlands eScience Center
//
// SPDX-License-Identifier: Apache-2.0

/**
 * Test generated by Google AI Mode based on the component code!
 * Slightly adjusted by Dusan to work as expected :-)
*/

import {renderHook, act, waitFor} from '@testing-library/react'
import React from 'react'
import {useForm, FormProvider} from 'react-hook-form'
import {useEditSoftwareBadges} from './useEditSoftwareBadges'
import {useSession} from '~/auth/AuthProvider'
import useSnackbar from '~/components/snackbar/useSnackbar'
import {
  getBadgesForSoftware,
  updateBadgePosition,
  deleteBadge,
  updateBadgeContent,
  addBadgeForSoftware
} from '~/components/software/apiSoftware'

// 1. Mock the API layer methods
jest.mock('~/components/software/apiSoftware', () => ({
  getBadgesForSoftware: jest.fn(),
  updateBadgePosition: jest.fn(),
  deleteBadge: jest.fn(),
  updateBadgeContent: jest.fn(),
  addBadgeForSoftware: jest.fn()
}))

// 2. Mock custom consumer hooks
jest.mock('~/auth/AuthProvider', () => ({useSession: jest.fn()}))
jest.mock('~/components/snackbar/useSnackbar', () => jest.fn())

const mockShowErrorMessage = jest.fn()
const mockInitialBadges = [
  {id: 'b1', badge_url: 'https://img.a', position: 1},
  {id: 'b2', badge_url: 'https://img.b', position: 2}
]

// 3. Create a wrapper component providing react-hook-form context
const Wrapper = ({children}: {children: React.ReactNode}) => {
  const methods = useForm({
    defaultValues: {
      id: 'soft-123',
      badges: mockInitialBadges
    }
  })
  return <FormProvider {...methods}>{children}</FormProvider>
}

beforeEach(() => {
  jest.clearAllMocks()
  ;(useSession as jest.Mock).mockReturnValue({token: 'secure-token'})
  ;(useSnackbar as jest.Mock).mockReturnValue({showErrorMessage: mockShowErrorMessage})
})

it('parses state parameters and handles unique url sets accurately', () => {
  const {result} = renderHook(() => useEditSoftwareBadges(), {wrapper: Wrapper})

  expect(result.current.badges).toEqual(mockInitialBadges)
  expect(result.current.urlsPresent.has('https://img.a')).toBe(true)
  expect(result.current.urlsPresent.has('https://img.b')).toBe(true)
  expect(result.current.modal.open).toBe(false)
})

it('opens and closes the editing modal window correctly', () => {
  const {result} = renderHook(() => useEditSoftwareBadges(), {wrapper: Wrapper})

  // Open modal step
  act(() => {
    result.current.openEditBadgeModal(mockInitialBadges[0])
  })
  expect(result.current.modal.open).toBe(true)
  expect(result.current.modal.data).toEqual(mockInitialBadges[0])

  // Close modal step
  act(() => {
    result.current.closeEditBadgeModal()
  })
  expect(result.current.modal.open).toBe(false)
  expect(result.current.modal.data).toBeUndefined()
})

it('updates badge tracking layouts optimistically during sorting runs', async () => {
  const {result} = renderHook(() => useEditSoftwareBadges(), {wrapper: Wrapper})
  const reorderedList = [mockInitialBadges[1], mockInitialBadges[0]]

  ;(updateBadgePosition as jest.Mock).mockResolvedValue(null)

  act(() => {
    result.current.handleSortedBadges(reorderedList)
  })

  // Verifies state was updated instantly
  expect(result.current.badges).toEqual(reorderedList)
  expect(updateBadgePosition).toHaveBeenCalledTimes(2)
})

it('updates existing badge content and reloads collection arrays on modal save calls', async () => {
  const {result} = renderHook(() => useEditSoftwareBadges(), {wrapper: Wrapper})

  // Create an updated version of an existing badge for the reload mock
  const updatedBadgePayload = {id: 'b1', badge_url: 'https://img.updated', position: 1}

  ;(updateBadgeContent as jest.Mock).mockResolvedValue(null)
  ;(getBadgesForSoftware as jest.Mock).mockResolvedValue([updatedBadgePayload, mockInitialBadges[1]])

  await act(async () => {
    await result.current.handleOnSaveBadge({
      badgeId: 'b1', // Signals an edit operation since badgeId is present
      badgeUrl: 'https://img.updated',
      altText: 'Updated Alt',
      badgeLink: 'https://link.updated'
    })
  })

  // 1. Verify the correct API method was dispatched with form values
  expect(updateBadgeContent).toHaveBeenCalledWith('secure-token', {
    badgeId: 'b1',
    badgeUrl: 'https://img.updated',
    altText: 'Updated Alt',
    badgeLink: 'https://link.updated'
  })

  // 2. Verify that creation logic was skipped entirely
  expect(addBadgeForSoftware).not.toHaveBeenCalled()

  // 3. Verify the layout reloads collections and closes the modal cleanly
  await waitFor(() => {
    expect(getBadgesForSoftware).toHaveBeenCalledWith('soft-123', 'secure-token')
    expect(result.current.badges[0].badge_url).toBe('https://img.updated')
    expect(result.current.modal.open).toBe(false)
  })
})


it('deletes targeted items and cascades index positional corrections', async () => {
  const {result} = renderHook(() => useEditSoftwareBadges(), {wrapper: Wrapper})

  ;(deleteBadge as jest.Mock).mockResolvedValue(null)
  ;(updateBadgePosition as jest.Mock).mockResolvedValue(null)

  await act(async () => {
    result.current.handleDeleteBadge('b1')
  })

  expect(deleteBadge).toHaveBeenCalledWith('secure-token', 'b1')

  // Wrap in a waitFor block so react-hook-form has time to apply the position updates
  await waitFor(() => {
    expect(result.current.badges).toEqual([
      expect.objectContaining({id: 'b2', position: 2})
    ])
  })
})


it('dispatches data additions and reloads collection arrays on modal save calls', async () => {
  const {result} = renderHook(() => useEditSoftwareBadges(), {wrapper: Wrapper})
  const freshBadgePayload = {id: 'b3', badge_url: 'https://img.c', position: 3}

  ;(addBadgeForSoftware as jest.Mock).mockResolvedValue(null)
  ;(getBadgesForSoftware as jest.Mock).mockResolvedValue([...mockInitialBadges, freshBadgePayload])

  await act(async () => {
    await result.current.handleOnSaveBadge({
      badgeId: null, // Signals brand new item injection branch loop
      badgeUrl: 'https://img.c',
      altText: 'New Alt',
      badgeLink: 'https://link.c'
    })
  })

  expect(addBadgeForSoftware).toHaveBeenCalledWith('secure-token', {
    softwareId: 'soft-123',
    badgeUrl: 'https://img.c',
    altText: 'New Alt',
    badgeLink: 'https://link.c',
    position: 3
  })

  // Ensures state collections trigger the refresh lifecycle fetch calls
  await waitFor(() => {
    expect(getBadgesForSoftware).toHaveBeenCalledWith('soft-123', 'secure-token')
    expect(result.current.modal.open).toBe(false)
  })
})
