# SPDX-FileCopyrightText: 2022 - 2026 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2022 - 2026 Netherlands eScience Center
# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 dv4all
# SPDX-FileCopyrightText: 2026 Dusan Mijatovic (Netherlands eScience Center)
#
# SPDX-License-Identifier: Apache-2.0

name: background-services sonar

on:
  workflow_run:
    workflows: ["background-services tests"]
    types:
      - completed

jobs:
  background-services-sonar:
    name: background-services sonar
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_java_sonar.yml
    with:
      head_sha: ${{ github.event.workflow_run.head_sha }}
      head_branch: ${{ github.event.workflow_run.head_branch }}
      working_directory: "background-services"
      # get artifacts saved in background_services_tests action (use same name)
      artifact_name: "background-services-target-dir"
      sonar_project_key: "nl.esciencecenter:background-services"
      workflow_run_id: ${{ github.event.workflow_run.id }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}