# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 Jurriaan Spaaks (Netherlands eScience Center) <j.maassen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2022 Netherlands eScience Center
# SPDX-FileCopyrightText: 2022 dv4all
#
# SPDX-License-Identifier: Apache-2.0

name: FAIR software

on:
  push:
    branches:
      - main
    paths:
      - README.md
  workflow_dispatch:

jobs:
  fair-software:
    name: "fair-software"
    runs-on: ubuntu-latest
    steps:
      - name: Setup howfairis configuration file
        run: echo 'skip_license_checks_reason: "We are following the REUSE specification for licenses"' > /fair.conf
      # https://github.com/fair-software/howfairis-github-action
      - name: Measure compliance with fair-software.eu recommendations
        uses: fair-software/howfairis-github-action@0.2.1
        env:
          PYCHARM_HOSTED: "Trick colorama into displaying colored output"
        run: howfairis "https://github.com/${{github.repository}}" --user-config-filename /fair.conf
