# SPDX-FileCopyrightText: 2022 - 2024 Netherlands eScience Center
# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 Jurriaan Spaaks (Netherlands eScience Center) <j.maassen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2022 dv4all
# SPDX-FileCopyrightText: 2024 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
#
# SPDX-License-Identifier: Apache-2.0

name: FAIR software

on:
  pull_request:
    branches:
      - main
    paths:
      - README.m
  workflow_dispatch:

jobs:
  fair-software:
    name: "fair-software"
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/fair-software/howfairis-github-action
      - name: Measure compliance with fair-software.eu recommendations
        uses: fair-software/howfairis-github-action@0.2.1
        env:
          PYCHARM_HOSTED: "Trick colorama into displaying colored output"
        with:
          MY_REPO_URL: "https://github.com/${{github.repository}}"
