# SPDX-FileCopyrightText: 2022 - 2023 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 - 2023 dv4all
# SPDX-FileCopyrightText: 2023 - 2026 Dusan Mijatovic (Netherlands eScience Center)
# SPDX-FileCopyrightText: 2023 - 2026 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2023 - 2026 Netherlands eScience Center
#
# SPDX-License-Identifier: Apache-2.0

name: frontend tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"

defaults:
  run:
    working-directory: frontend

jobs:
  # CHECK 1: Linter
  fe-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: "install node and cache npm"
        uses: actions/setup-node@v6
        with:
          node-version: 24.14
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: "install dependencies"
        run: npm ci
      - name: "run eslint check"
        run: npm run lint

  # CHECK 2: Unit Tests
  fe-test:
    name: "fe-test"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: "install node and cache npm"
        uses: actions/setup-node@v6
        with:
          node-version: 24.14
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: "install dependencies"
        run: npm ci
      - name: "run unit test"
        run: npm run test:coverage

      # Save PR info inside the coverage directory for frontend_sonar.yml to use
      - name: Save PR info
        run: |
          mkdir -p coverage
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "${{ github.event.pull_request.number }}" > coverage/pr_number.txt
            echo "${{ github.event.pull_request.base.ref }}" > coverage/pr_base.txt
            echo "PR_NUMBER: ${{ github.event.pull_request.number }}"
          else
            echo "false" > coverage/pr_number.txt
            echo "false" > coverage/pr_base.txt
            echo "Not a pull_request. Event: ${{ github.event_name }}"
          fi
      # Upload the coverage folder for SonarCloud (fe-sonar) to use
      - name: "upload coverage artifact"
        uses: actions/upload-artifact@v7
        with:
          name: frontend-coverage
          path: frontend/coverage/
          # Automatically clean up after 24 hours
          retention-days: 1

  # CHECK 3: Build Verification
  fe-build:
    name: "fe-build"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: "install node and cache npm"
        uses: actions/setup-node@v6
        with:
          node-version: 24.14
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: "install dependencies"
        run: npm ci
      - name: "run build test"
        run: npm run build
