
name: docker build frontend

on:
  push:
    branches:
      - release
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "get-npm-version"
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: frontend
      - name: "show version number"
        run: echo build rsd-saas/frontend:${{steps.package-version.outputs.current-version}}
      - name: "build the frontend docker image"
        run: |
          IMAGE_TAG=ghcr.io/research-software-directory/rsd-saas/frontend:${{steps.package-version.outputs.current-version}}
          echo image_tag $IMAGE_TAG
          docker build -t $IMAGE_TAG -f frontend/Dockerfile ./frontend
      - name: "login to ghcr"
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{github.actor}} --password-stdin
      - name: "push image to ghcr"
        run: |
          IMAGE_TAG=ghcr.io/research-software-directory/rsd-saas/frontend:${{steps.package-version.outputs.current-version}}
          echo image_tag $IMAGE_TAG
          docker push $IMAGE_TAG


