# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 dv4all
# SPDX-FileCopyrightText: 2026 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2026 Netherlands eScience Center
#
# SPDX-License-Identifier: Apache-2.0

name: "REUSE Compliance Check"

on:
  # moved to manual
  # pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: "actions/checkout@v6"
    - name: "REUSE Compliance Check"
      uses: "fsfe/reuse-action@v6"
