FROM maven:3.8.3-openjdk-17
WORKDIR /usr/mymaven
RUN mkdir --parents ./src/main
COPY authentication/pom.xml .
RUN mvn clean package -Dmaven.main.skip -Dmaven.test.skip && rm -r ./target && mvn exec:java --fail-never
COPY authentication/src/main ./src/main
COPY frontend/.env.production.local .
CMD mvn compile && mvn exec:java -Dexec.args=$PROPERTIES
